- layers/draw_state.cpp
- layers/draw_state.h
- layers/vk_validation_layer_details.md
- tests/layer_validation_tests.cpp
Series adds Tobin's DrawState validation checks for push constants, and additional ShaderChecker checks for consistency between the shader's push constant usage and the pipeline layout.
> Validation of push constants

- layers/core_validation.h
warning 4577: 'noexcept' used with no exception handling mode specified
In ANGLE we use the _HAS_EXCEPTIONS=0 macro in many places since we build without exceptions. This fixes a warning that occurs in conjunction with this define.
> layers: Fix MSVS noexcept warning in core_validation.

- layers/core_validation.cpp
- layers/core_validation.h
mem_tracker layer had specific maps to track memory binding for images
and buffers. This change merges the data from those maps into IMAGE_NODE
and BUFFER_NODE respectively and eliminates the binding maps.
> layers: Merge binding maps into image and buffer maps

- layers/core_validation.cpp
- tests/layer_validation_tests.cpp
These types consume two locations per vector. Both the VI and the VS sides were incomplete. This fixes #391
> Fix location counting for 3- and 4-component vectors (and aggregates of these)

- layers/core_validation.cpp
- layers/core_validation.h
- layers/device_limits.cpp
- layers/image.cpp
- layers/object_tracker.h
- layers/parameter_validation.cpp
- layers/vk_layer_logging.h
- layers/vk_layer_table.cpp
- vk-layer-generate.py
- vk_helper.py
1) Introduce convention of explicitly placing "0x" before hex
format requests for clarity (don't use "%#")
2) All lower case in hex output (except w/stringstream which refuses
to do anything but uppercase, possibly only on windows).
3) Decorated pointers are printed for all Vulkan structure types.
3) Some intelligence in generators based on Vulkan variable name:
if the Vulkan variable name contains ("flag", "bit", "offset",
"handle", "buffer", "object", "mask") it will be output in
hexadecimal format
Change-Id: Idbae73bfdaa3bc059543d43b209373cd0bcbc099
> layers:LX#470 Address poor use of hex vs dec output & w/a convention

- tests/layer_validation_tests.cpp
Add test for case where a non-NULL pNext value points to a structure
that is not valid for the current struct type.
VkPipelineRasterizationStateCreateInfo::pNext is currently only
allowed to point to VkPipelineRasterizationStateRasterizationOrderAMD.
Setting pNext to a structure of any other type should generate an
error.
> tests: Add invalid pNext test

- generator.py
- layers/parameter_validation.cpp
Add special handling to the parameter_validation layer's code
generator for vk.xml parameters with the 'noautovalidty' attribute:
- Ignore vk.xml parameters with the 'noautovalidity' attribute
when generating code for the parameter_validation layer.
- Implement custom validation routines for parameters with
'noautovalidity' tags.
> layers: Ignore 'noautovalidity' params w/codgen

- layers/descriptor_sets.h
Was missing IsImmutableSampler() override function for the
ImageSamplerDescriptor class.
> layers: Fix ImageSampler immut sampler check

- generator.py
- layers/parameter_validation.cpp
Apply 'noautovalidity' code generation logic to struct members.
Previously, struct pointers tagged as noautovalidity were ignored by
the code generator, but the members of non-NULL struct pointers
were still processed.  Now both the struct pointer and the struct
members are ignored when the struct pointer has the 'noautovalidity'
attribute.
> Expand noautovalidity processing for structs

- demos/CMakeLists.txt
- loader/CMakeLists.txt
Fix the CMake code that overrides the /MD flag with the /MT flag for
the Windows demo and loader projects.  The CMake debug and release
variables were set to /MTd and /MT, overriding all existing debug
and release settings.
Now replacing /MD with /MT in the debug and release variables,
without losing other debug/release settings.  Also performing
the MD/MT substitution for all release and debug configurations.
> cmake: Fix MSVCRT override

- tests/layer_validation_tests.cpp
As @ratchetfreak points out, this self-dependency and barrier were
invalid per 6.5.1: "Self-dependencies must only include pipeline stage
bits that are graphics stages".
Signed-off-by: Chris Forbes <chrisforbes@google.com>
> tests: Fix subpass self-dependency and barrier in test

- layers/parameter_validation.cpp
Make parameter validation logic for VkImageSubresource ignore
layerCount when it is set to VK_REMAINING_ARRAY_LAYERS.
> layers: Handle special layerCount case

- vk-layer-generate.py
Fixes #756 
This is similar to #750 but it's an issue for non-dispatchable handles in unique_objects.
Update the codegen for Destroy functions to remove the handle from the map prior to calling down the chain.
> Tobin gh756 unique obj free destroy cleanup

- layers/threading.cpp
- tests/layer_validation_tests.cpp
Update threading layer data structures before calling down to FreeCommandBuffers.
That avoids a race condition with reuse of freed command buffer handles.
Use calls to vkEnumeratePhysicalDevices to reliably enable threading checks
in validation test before attempting to trigger a validation report.
> Stroyan threading cmd reuse

- layers/core_validation.cpp
- tests/layer_validation_tests.cpp
Fixes #601 
The pClearValues array is indexed by the attachment index which
means that it must be at least as large as the last LOAD_OP_CLEAR
attachment in the renderpass. Updating this check to reflect this
requirement.
> layers: Update clearValueCount check

- layers/unique_objects.h
- tests/layer_validation_tests.cpp
- vk-layer-generate.py
Add ID substitution support for the VkDedicatedAllocationMemoryAllocateInfoNV extension structure to the unique_objects layer.  The current implementation is specific to the case where the vkAllocateMemory function's pAllocateInfo parameter references a single VkDedicatedAllocationMemoryAllocateInfoNV struct.
> Add NV_dedicated_allocation support to unique_objects layer

- generator.py
- layers/parameter_validation.cpp
- layers/parameter_validation_utils.h
- tests/layer_validation_tests.cpp
- vk.xml
Change the severity level of the parameter_validation layer's pNext parameter validation messages from error to warning.  Also add the following explanation that the warning is derived from the Valid Usage
language from version X of the Vulkan spec/header: 
>This warning is based on the Valid Usage documentation for version %d of the Vulkan header.  It is possible that you are using a struct from a private extension or an extension that was added to a later
version of the Vulkan header, in which case your use of pNext is perfectly valid but is not guaranteed to work correctly with validation enabled
Issues-Addressed: LunarXchange 560
> layers: Change pNext validation error to warning

- layers/core_validation.cpp
- layers/core_validation.h
- layers/core_validation_types.h
- layers/descriptor_sets.cpp
- layers/descriptor_sets.h
- tests/layer_validation_tests.cpp
Fixes #762, and lays a lot of groundwork for other image usage validation that @tobine has wanted for a while.
> Impose requirements on descriptors from spirv image types

- layers/object_tracker.h
This moves a static array of maps to be a vector of maps.
Building android from Windows crashes clang without this change.
clang in the NDK doesn't like arrays of unordered_maps.
> layers: Fix object_tracker build

- layers/core_validation.cpp
- layers/core_validation_types.h
Fixes #821 
The first and last CLs are the important ones. Just some clean-up in-between.
Kill single "image" member from DEVICE_MEM_INFO struct as all bound images are now correctly tracked in object_bindings set.
Update the validation check at MapMemory time to verify that ANY images that overlap the mapped memory are in the correct image layout.
> Tobin gh821 multiple img mem mapping

- layers/core_validation.cpp
Fixes #846 
Use IMAGE_USAGE bits for images. Capitalize some functions while I'm at it.
> Tobin gh841 enum fix

- layers/parameter_validation.cpp
- layers/parameter_validation_utils.h
- layers/vk_layer_table.cpp
Enabled Parameter Validation of WSI functions.  The swapchain layer PR #834 is dependent upon this change.
I've run Windows and Linux here, but it'd be great if you could run it through your farm, please.
> layers: Add WSI support to parameter_validation

- layers/core_validation.cpp
- layers/core_validation_types.h
- tests/layer_validation_tests.cpp
This moves memory allocation valid tracking to be per-range instead of per allocation. Also improves alias tracking but lots more work to do in that department. It does fix a couple of errors in how invalid alias cases were being flagged.
This should fix #605 with current changes, but still need to fix the failing test.
Noted various holes with TODOs.
> Tobin gh605 mem valid per range

- tests/layer_validation_tests.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
Add ability to pass VkPhysicalDeviceFeatures to InitState to control which features are enabled when creating m_device.  The tradeoff for this is that we must now call InitState() if we wish to use m_device
> Add device features to InitState

- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/descriptor_sets.cpp
- layers/descriptor_sets.h
When dealing with dynamic offsets, the binding numbers, and array indices within
a binding, are all sequential.
This is according to the spec "Descriptor Set Binding" section which states,
"...entries are ordered by the binding numbers in the descriptor set layouts; and
within a binding array, elements are in order."
This means when processing the binding numbers to validate the dynamic offsets at
draw time, we should do so in order to make sure that the sequential dynamic offset
index correctly correlates with the dynamic offset being processed.
> layers: Update descriptor binding to use an ordered map

- layers/core_validation.cpp
- tests/layer_validation_tests.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
If the subpass uses a depth/stencil attachment and rasterization is not
disabled, then this structure must be present.
> layers: Require VkGraphicsPipelineCreateInfo::pDepthStencilState

- tests/layer_validation_tests.cpp
This won't give us test failures yet, but does make the spurious errors
visible.
> tests: Complain about unexpected errors

- layers/core_validation.cpp
- layers/vk_layer_utils.cpp
- layers/vk_layer_utils.h
Added missing BC1_RGBA formats to vk_format_is_compressed function
Added function in vk_layer_utils to get block sizes for compressed formats
These changes address the issues discussed in GH-951 (https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/951)
> GH-951 - Improve validation for minImageTransferGranularity

- layers/core_validation.cpp
- tests/layer_validation_tests.cpp
WIP
MarkL, please check this out. I don't think it's quite right yet, but I got a bug report related to this code and I think there are definitely some issues.
Checks for underflow and overflow when flushing mapped memory weren't properly handling
offset. Underflow check should go from the base of the shadow memory to the range offset.
The overflow check should go from the end of the mapped memory range to the end of the
shadow memory.
Finally, when copying the region, the start address of the copy should include offset.
> layers: Fix state tracking for vkFlushMappedMemoryRanges()

- layers/README.md
- layers/vk_layer_config.cpp
Add the VK_LAYER_SETTINGS_FILE environment variable, which specifies an a file path to be used in the place of vk_layer_settings.txt. If the environment variable isn't found, the layers revert to the old behavior (vk_layer_settings.txt in the working directory).
This fixes #983
> Add environment variable for alternate vk_layer_settings.txt

- layers/descriptor_sets.cpp
- tests/layer_validation_tests.cpp
Fixes #1034 
Adds new check to make sure STORAGE_IMAGE descriptors are only updated with GENERAL image layout along with associated test.
> Tobin gh1034 storage image layout check

- layers/core_validation.cpp
Add VKAPI_ATTR to FlushMappedMemoryRanges and
InvalidateMappedMemoryRanges function declarations.
> layers: Fix core_validation function declarations

- layers/core_validation.cpp
- layers/descriptor_sets.cpp
- layers/image.h
- layers/vk_validation_layer_details.md
- tests/layer_validation_tests.cpp
Expand abbreviations to improve readability:
DS=depth/stencil
DS=descriptor set
CB=command buffer
VS=vertex shader
FS=fragment shader
VTX=vertex
PSO=pipeline state object
Change-Id: I48fe917aac50d1911fe2a3aa1ed2c739637c7645
> layers: Reword from cryptic abbreviations to readable words

- tests/layer_validation_tests.cpp
Continuation of commit d793351
Expand abbreviations to improve readability:
PSO -> pipeline state object
w/o -> without
Change-Id: Ia0281b4d2dc00541a70bc48710daa0ffd89d9117
> tests: Expand PSO abbreviation for readability

- layers/core_validation.cpp
Throwback Monday.  If a custom allocator is used and fails, validation will continue and use a null pointer, leading to invalid/unuseful validation errors. Added a check for a good return code.
> GH321, vkAllocateMemory return code handling

- demos/smoke/Game.cpp
Replaced snprintf with stringstream.
> demos: Fix compiler warning in smoketest

- demos/vulkaninfo.c
Swapchain present modes are now displayed with the other surface information.
Variable and functions renamed to match the Google c++ style guide.
> vulkaninfo: Add surface present modes and fix variable/function names

- layers/object_tracker.cpp
- layers/spec.py
- layers/vk_validation_error_messages.h
Add VALIDATION_ERROR_UNDEFINED to UNIQUE_VALIDATION_ERROR_CODE enum
with a value of "-1". This had been custom-defined in
object_tracker.cpp so removing it from there.
> layers:Add undefined validation error enum

- layers/core_validation.cpp
See #1259 
This is a couple of simple updates to improves handling of aliasing in the validation layers.
Change an error to a warning and initialize a variable.
> Tobin gh1259 aliasing

- layers/descriptor_sets.cpp
- layers/descriptor_sets.h
Fixes #1227 
Store bindings in-order in DescriptorSetLayout class.
This simplifies the class a bit and allows easy check for consecutive binding order. I looked at further consolidating the class to unify the *FromIndex & *FromBinding functions but b/c bindings may still have gaps it's friendlier to users of the class to provide both functions.
> Tobin descriptor layout bindings in order

- layers/core_validation.cpp
- layers/core_validation_types.h
Now that cmd buffer printing has been removed, the only use of this is
to distinguish between cmd buffers invalidated before and after a
complete recording. This should eventually be folded into the state
machine, but removing the vector of cmds is a first step.
Signed-off-by: Chris Forbes <chrisforbes@google.com>
> layers: Remove cmds vector from GLOBAL_CB_NODE

- layers/image.cpp
- layers/parameter_validation.cpp
- layers/threading.cpp
- scripts/vk_helper.py
struct_validate_helper was unused, enum_validate_helper was only used for redundant checks that have been removed/replaced.  Part of switching vk-helper stuff over to being vk.xml-based.
> Remove redundant image layer checks, remove enum/struct_validator_helpers

- layers/CMakeLists.txt
Remove old dependencies from cmake, which was causing long build times
even when nothing had changed.
Change-Id: Ie162606b54352306ae6400aa18e942d8cffb7782
> cmake: speed up the build

- tests/layer_validation_tests.cpp
This does not actually fix the Unexpected error message, 
since the real problem is in the validation layers... 
The call to vkQueueSubmit is triggering 2 error messages.
Is one redundant?
Change-Id: I4e28cc778dff7581c83cbe53240d1706f60253a7
> tests: Insert missing vkQueueWaitIdle()

- layers/vk_layer_utils.cpp
- loader/loader.c
The string length validation will not detect strings
that exceed the max length.
For example, when i = max_length-1 and utf8[i] is a valid
character (>= 0x20 and < 0x7f) no error is thrown and
the next iteration will end the loop.
This change extends the loop and the if check to
catch this issue.
And, BTW, it's not really necessary to put the validation check here as neither issue will cause the loader to crash. That allows this test to be moved to a validation layer where it really should be.
> loader: Fix validation error

- update_external_sources.sh
Python is built-in on Macs; this avoids an unnecessary dependency on greadlink
> Use Python instead of greadlink to get full path on macOS

- layers/core_validation.cpp
Fixes #1311
In the Draw-time refactor the marking of store images and buffers as
written was incorrectly moved before the list of images and buffers was
updated for the current active bindings.
This fix restores correct order of operations so that the buffers and
images of interest are first added to cmd buffer active list, then
they're appropriately updated as written.
> layers:Mark latest buffers and images as written

- tests/layer_validation_tests.cpp
TestAliasedMemoryTracking has an early exit case that was failing to
free allocated memory. This was leading to a fail on some platforms.
> tests:Clean up memory on early exit

- scripts/vk_helper.py
VkSubmitInfo->pWaitDstStageMask should be treated as a dynamic array with a count of VkSubmitInfo->waitSemaphoreCount.  Passes all tests on the LunarG farm and trace/replay tests on VulkanTools.
> scripts: Fix vk_helper.py dynamic array determination

- demos/cube.c
- demos/cube.cpp
Fixes #1316.
Rework XCB event processing code to handle events
properly and avoid hangs when pausing.
Fix polarity of decrease/increase spin rate keys.  I
suspect that this was an artifact from fixes made
to the transforms a while back.
Change-Id: I74adf7309227fafd175d8972ca930a304c58a1dd
> demos: Make spacebar pause work in cube demo (Linux).

- layers/object_tracker.cpp
Fixes #1342.  The IndirectCountAMD extension used the wrong object type for validating its command buffers.
> GH1342, Correct the objecttype in object_tracker

- demos/smoke/Game.h
- demos/smoke/Smoke.cpp
- demos/smoke/Smoke.h
Running smoketest with --flush will call vkFlushMappedMemoryRanges so
that the trace layer is aware of modified memory. This is not
necessary with the --PMB option in vktrace.
Change-Id: If72c0ed0c651cf82f2f2c4c78ec2534a0d475a9c
> demos: smoketest: Add --flush option for tracing

- loader/debug_report.c
- loader/extensions.c
- loader/loader.c
- loader/vk_loader_platform.h
Handle possible null pointer dereferences.
Misc other warnings, nothing too serious.
Not addressing alloca concerns yet.
Change-Id: I712a6b4996a4d900604867e373521ff4d1c53df5
> loader: Fix static analysis warnings

- tests/layer_validation_tests.cpp
Use of the gtest FAIL() macro within VerifyFound() and
VerifyNotFound() caused it to abort after first message,
and skipped the Reset() call. (FAIL macro decodes to return).
Replaced with ADD_FAILURE() which records the failure
but doesn't abort the reporting loop.
Change-Id: I71fff87609e093e96d1186f24338fe04f3346b66
> tests: Replace FAIL() macro in ErrorMonitor

- layers/spec.py
The vk_validation_error_messages.h header file now disables clang-format.
> Disable clang-format for in-source generated header

- loader/LoaderAndLayerInterface.md
The layers are not "inside" the loader as was implied by the previous language.
Add missing markup so that the `<abi version>` portion of the loader filename renders correctly in a web browser.
> loader: Minor language clarification, fix markup.

- tests/layer_validation_tests.cpp
Provide another early exit condition if memory allocation fails
and make sure all objects are cleaned up for early exit cases.
> tests:Update error handling for DSBufferLimitErrors

- tests/layer_validation_tests.cpp
These ifdefs are no longer useful for their original purpose.
> Remove obsolete test-ifdefs from LVTs

- layers/object_tracker.cpp
Update GetPhysicalDeviceQueueFamilyProperties() in object_tracker to
verify that physicalDevice is valid.
> layers:Add physicalDevice check

- layers/parameter_validation.cpp
- scripts/parameter_validation_generator.py
The procedure map is now generated instead of being hard-coded.  This also uncovered several missing entrypoints for a couple of extensions -- indirect count and display control, which have been added.
> Parameter Validation updates for increased automation and additional extensions

- layers/parameter_validation.cpp
- tests/layer_validation_tests.cpp
Undefined shouldn't be an error since its a valid enumerant.
Change-Id: I542b47cdf885bd9ccb96a0a113a56a849423800a
> tests: Fix UnusedPreserveAttachment

- loader/loader.c
Fixes #1474
Fix path parsing code to handle leading and trailing
path separators.  Also handle contiguous path separators.
When encountering something like ::: in the path, the old
code would add multiple entries containing only the
relative part of the path (e.g., /vulkan.icd.d).
> loader: Fix XDG path parsing

- layers/buffer_validation.cpp
- layers/buffer_validation.h
- layers/core_validation.cpp
- layers/core_validation_types.h
Refactored FillBuffer to split validation from state updates, added pre/post routines.  Moved these, along with validate and record routines from several other image/buffer APIs into buffer_validation and updated for style.
This is pretty much it, buffer_validation-wise, except for CopyImageToBuffer and CopyBufferToImage.
> Refactor CmdFillBuffer, move Destroyimage/buffer/imageview/bufferview routines

- CMakeLists.txt
- loader/loader.c
This makes it easier for non-FHS distributions to behave well when the loader is used by a SUID process or in an otherwise unusual environment.
> loader: Configurable fallback search paths

- tests/CMakeLists.txt
After my fifth time of forgetting to rebuild the layers before running the validation tests, I decided to add an explicit build dependency in CMake. I figured it might help others as well, but feel free to reject if it doesn't seem useful.
> tests: vk_layer_validation_tests depends on layer targets.

- layers/core_validation.cpp
Reorder the fields to match the declaration, initialize tiling & type.
Previously the image type ended up as VK_IMAGE_TYPE_1D due to the
default initialization, which caused bad behavior in later validation.
Fixes #1508.
> layers: Fix state recorded for swapchain images

- layers/threading.cpp
- scripts/threading_generator.py
This API is a special-case for the code-gen in that it sometimes returns an array of images. These do not need to be counted by start/finishReadObject and so were moved into the non-generated part of the layer source.
Tony is going to test this by running CTS overnight.
>  Special-case threading layer GetSwapchainImages call

- layers/core_validation.cpp
- tests/layer_validation_tests.cpp
When using this sharing mode, buffers and images are created with a list of valid queue families.  Check that when a CB uses these objects that they're valid for the current queue.
> Buffer/Image checks for SHARING_MODE_CONCURRENT

- tests/layer_validation_tests.cpp
This test intentionally exceeds the limits of framebuffers, which infers
some precarious constraints on attachments.
Change-Id: If98a9e7907ca2219d8c09c8f4264560e7cf41c89
> tests: Fix FramebufferCreateErrors errors

- layers/core_validation.cpp
- tests/layer_validation_tests.cpp
@jeremy-lunarg this builds on your PR #1519 . Now that we're not doing anything extra in this function, all the open-coding can just go away.
> Remove more redundancy in IncrementBoundObjects

- layers/buffer_validation.cpp
- tests/layer_validation_tests.cpp
Remove redundant validation from ValidateCmdBufImageLayouts.
Change-Id: Ia7474e0ca7d0429a8413500f548e1cfbe9f708f1
> layers: Remove redundant validation

- scripts/loader_extension_generator.py
The loader code generation scripts had a bug that
caused all the surface->ICD surface translation C
code to be placed inside a block that only ran if
the ICD didn't support the extension function,
making it effectively a no-op.  ICDs that
supported the extension were instead called with
the un-translated surface handle, which could
cause a crash if they were expecting their local
surface handle.
Also, speculatively fix up return handling in this
same class of functions by handling the void
return type.
> loader: Fix handling of surface parameters

- layers/unique_objects.cpp
- layers/unique_objects.h
- scripts/helper_file_generator.py
- scripts/unique_objects_generator.py
The UniqueObjects utility layer needed to unwrap vulkan object handles embedded in a buffer parameter of `vkUpdateDescriptorSetWithTemplateKHR()`.  This patch series parses that buffer, replacing the uniquified handles with the actual ones before passing the call to the hardware.  This takes care of part of issue #1529.
> Add ability to handle DescriptorUpdateTemplate extension to unique objects layer

- build-android/update_external_sources_android.sh
The command is more widely available in Linux since it is part of Coreutils.
Followup to: https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1532
> Use nproc instead of ncpu

- layers/core_validation.cpp
- layers/descriptor_sets.cpp
- layers/descriptor_sets.h
Changes to address feedback on CV UpdateTemplate changes.  @tobine, the only things I knowingly left out are the ObjectTracker updates for this new object and the validation check you mentioned for the getnextvalidbinding call.
There is a process issue getting new object types into the debug-report extension object type enums.  This'll be solved long term by getting a standalone object list enum into the vulkan header, or by us generating one.  This applies to all new extensions containing new objects.
I left out the validation check since this was the record path.  Will this get covered when validation is added?
> Refactor UpdateTemplate changes for DescriptorSet module

- include/vulkan/vk_icd.h
I messed up the amend, was #1563.
> headers: Add missing include to vk_icd.h

- layers/parameter_validation.cpp
- tests/layer_validation_tests.cpp
If this extension is enabled, negative viewports should not trigger validation errors.  Added mod to parameter_validation layer and a new maintenance1-specific test class and test for this.
> Add Maintenance1 Extension tolerance for negative viewport heights

- include/vulkan/vulkan.h
- include/vulkan/vulkan.hpp
- layers/linux/VkLayer_core_validation.json
- layers/linux/VkLayer_object_tracker.json
- layers/linux/VkLayer_parameter_validation.json
- layers/linux/VkLayer_swapchain.json
- layers/linux/VkLayer_threading.json
- layers/linux/VkLayer_unique_objects.json
- layers/object_tracker.cpp
- layers/parameter_validation.cpp
- layers/windows/VkLayer_core_validation.json
- layers/windows/VkLayer_object_tracker.json
- layers/windows/VkLayer_parameter_validation.json
- layers/windows/VkLayer_swapchain.json
- layers/windows/VkLayer_threading.json
- layers/windows/VkLayer_unique_objects.json
- loader/CMakeLists.txt
- scripts/cgenerator.py
- scripts/vk.xml
- tests/layers/linux/VkLayer_test.json
- tests/layers/linux/VkLayer_wrap_objects.json
- tests/layers/windows/VkLayer_test.json
- tests/layers/windows/VkLayer_wrap_objects.json
This update killed a couple of KHX extension APIs and added three new APIs from two new extensions.
> Update Vulkan-LVL to 1.0.43 version of the header

- loader/loader.c
Fields of json_version were left uninitialized if file_format_version
in a layer json file was incomplete.  Initialize them to 0.
> loader: Initialize json_version

- demos/cube.c
- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/descriptor_sets.cpp
- layers/descriptor_sets.h
Finally getting around to piping this in. Only current option is to disable all of the flags that are present in validation which don't cover all of the validation checks, but is a nice POC to at least have something working. Tested with an update to cube that turns on validation and sets the VK_VALIDATION_CHECK_ALL_EXT enum of VK_EXT_validation_flags.
> Tobin val flags piping

- layers/unique_objects.cpp
Testing the template object handling for BufferViews necessitated some pointer math changes.  This fixes #1583.
> Fix CTS BufferView UpdateTemplate crash

- layers/swapchain.cpp
This fixes LunarXchange issue 660: https://vulkan.lunarg.com/issue/view/58c17d02e46ffe6c91bc8ccc
VK_KHR_get_physical_device_properties2 extension adds a new API to get the device queue family properties.  The swapchain layer needs record the number queue families in this function this so it can correctly validate the queue family index in GetPhysicalDeviceSurfaceSupportKHR.
> Add GetPhysicalDeviceQueueFamilyProperties2KHR to swapchain

- layers/unique_objects.cpp
- scripts/unique_objects_generator.py
Unique_objects layer code-gen ignored these APIs as their handles are embedded in a structure and aliased. Added manual coverage.
Rolando/Baldur -- can you guys see if this patch takes care of the issue you are seeing? 
Fixes #1592
> Add unique_objects DebugMarker Extension special-cases

- tests/layer_validation_tests.cpp
Fixed an error in RenderPassInUseDestroyedSignaled that was causing
a benign failure on most devices but throwing an exception on Intel
Windows driver.
Change-Id: I985429e1bf20f68710faf2012a201a18b4648939
> tests: Fix UnexpectedError crashing on WinIntel

- layers/unique_objects.cpp
Exact same if check performed multiple times.
Removing redundant one
Change-Id: Iff32a724e58a06b4a967ba2632e60cc5b4050238
> layers: Removing redundant if in unique_objects

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/descriptor_sets.cpp
Skip checks that are no longer valid if the VK_KHR_maintenence1 extension is enabled.  Additional validation checks required for VK_KHR_maintenence1 will be provided in a later patch set.
> Remove VK_KHR_maintenence1 false positives

- layers/parameter_validation_utils.h
- tests/layer_validation_tests.cpp
Fixes #1621.  Cyclic pNext chain errors would crash/lock up the layers.  Added check, error message and early exit.  Also plumbed in similar check for duplicates in the pNext chain, which is about to be added to the spec, along with a matching test.
> Layers: Add check for cyclic pNext chains, and duplicate pNext structures

- layers/core_validation.cpp
- layers/core_validation_types.h
Using any of these extensions resulted in incorrect validation errors.
> Add extension shader caps coverage to core validation

- layers/unique_objects.cpp
- scripts/parameter_validation_generator.py
- scripts/unique_objects_generator.py
Fix code generation for extension functions receiving struct parameter types defined by core Vulkan.  
Extensions are processed as separate features by the code generator, and the type info required for struct processing was not being shared across features.  The code generator has been modified to share type info across features so that the validation code generated for extension functions includes validation for core structures:
- Prevent unique objects and parameter validation code generators from
clearing struct type info data structures at the start of feature
processing.
- Remove unused data structures from unique objects code generator.
- Adds handle unwrapping and parameter validation for elements in the
vkCmdPushDescriptorSetKHR pDescriptorWrites parameter.
- Adds handle …
> layers: Fix extension func/core struct codegen

- layers/object_tracker.cpp
Three extensions have been added that get VkSurface objects for various operating environments. Added functions to object_tracker  to catch the creation of these Vulkan objects to prevent spurious validation errors. Extensions are VK_NN_vi_surface, VK_MVK_ios_surface and VK_MVK_macos_surface.
> Add ios, mac and nintendo extension surface tracking

- tests/layer_validation_tests.cpp
- tests/vkrenderframework.cpp
Added an assert in render framework to flag an InitFramework() call
when the VkInstance is already initialized. Re-initializing without an
explicit shutdown was leaking Vk* resources and sowing potential ICD 
confusion. Fixed a few tests that tripped the assert.
> tests: Add assert for multiple initializations

- demos/cube.c
- include/vulkan/vulkan.h
- include/vulkan/vulkan.hpp
- layers/core_validation.cpp
- layers/linux/VkLayer_core_validation.json
- layers/linux/VkLayer_object_tracker.json
- layers/linux/VkLayer_parameter_validation.json
- layers/linux/VkLayer_swapchain.json
- layers/linux/VkLayer_threading.json
- layers/linux/VkLayer_unique_objects.json
- layers/object_tracker.cpp
- layers/parameter_validation.cpp
- layers/windows/VkLayer_core_validation.json
- layers/windows/VkLayer_object_tracker.json
- layers/windows/VkLayer_parameter_validation.json
- layers/windows/VkLayer_swapchain.json
- layers/windows/VkLayer_threading.json
- layers/windows/VkLayer_unique_objects.json
- scripts/vk.xml
- tests/layers/linux/VkLayer_test.json
- tests/layers/linux/VkLayer_wrap_objects.json
- tests/layers/windows/VkLayer_test.json
- tests/layers/windows/VkLayer_wrap_objects.json
Moved to 1.0.46 version of the header, pulled in new validation checks for the `VK_KHR_incremental_present` extension as well as related demo changes.
This supersedes #1643.
> Update to 1.0.46 Header PLUS Incremental_Present extension updates

- CMakeLists.txt
- build-android/android-generate.bat
- build-android/android-generate.sh
- scripts/helper_file_generator.py
- scripts/lvl_genvk.py
We have been using the DebugReportObjectType enums in the layers to handle object types.  This worked fine until extensions began adding new objects.  New object type enum entries are added via the 'extends' mechanism in the spec generator, meaning that the integer values for the new types start in the billion-range leading to very sparse arrays and greatly complication their usage for validation layers.
The purpose of this PR is to have the build generate a header file containing the definition of a packed enumerated type covering all of the defined Vulkan Objects, along with a conversion routine which will translate one of these enums to the corresponding Vulkan Debug Report object type. These will not/should not be shared among a layer and any other layer, loader, driver, etc. and are …
> Add code generation for internal layer object type definitions

- layers/buffer_validation.cpp
- layers/buffer_validation.h
- layers/core_validation.cpp
Streamline some of the image layout validation code. At the time of
CmdBeginRenderPass() remove the layout transition from validation code
and perform the layout transitions all at once.
This allows a bit of transition code to be killed so that the initial
transition code can share TransitionSubpassLayouts() function.
> layers:Refactor image layout validation

- layers/object_tracker.cpp
- layers/object_tracker.h
- scripts/helper_file_generator.py
- tests/layer_validation_tests.cpp
Updated OT to use the layer object type enum instead of the debug-report object type enum.  Also fixed up some variable names, added coverage for new object types, and added a string helper function to the codegen.
This passes cleanly on our farm, but as there are new object types Tony as (graciously!) volunteered to run these changes through CTS tonight to check for regressions.
> ObjectTracker Update: Type Enums and variable names

- layers/buffer_validation.cpp
- layers/buffer_validation.h
- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/descriptor_sets.cpp
- layers/descriptor_sets.h
- tests/layer_validation_tests.cpp
Fixes #1476 
Validate that image layout specified in image descriptor update matches actual layout at draw time.
Also add a test to verify this case.
There's spec language for this but not a specific VU so I'll make a spec MR for that separately and then update the check/test to include that VU when it's in.
> Tobin gh1476 ds image layout val

- layers/core_validation.cpp
INFO message in vkCreateDescriptorPool() is not needed and it was
returning a validation error if the callback returned "true" which is
just wrong. Killing the code altogether.
> layers:Remove old INFO message

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/descriptor_sets.cpp
- layers/parameter_validation.cpp
Except for `swapchain.cpp`, which is/might be undergoing a merge into CV.
This is a straight global S&R with clang-format.
> Banish 'skip_call' once and forever

- tests/layer_validation_tests.cpp
If semaphores.size() == 1, we'd call operator[] with -1. You get away
with this on most STLs, but the MS debug STL (right) complains that this
is nonsense.
> tests: Fix LongSemaphoreChain bad indexing

- demos/cube.c
- demos/cube.cpp
It is currently impossible to reliably throttle presentation per the
Vulkan spec.
The previous code was relying on fences returned by
vkAcquireNextImageKHR() to throttle.  The only information this fence
holds is whether it is possible to render to that image since the *last
time* it was presented, which could have happened several frames ago.
Instead, we can throttle the rendering by passing a fence to
vkQueueSubmit().
The previous code (only the cube.c version) was using a fence there to
synchronize a vkMapMemory() in demo_update_data_buffer(), which doesn't
seem necessary.
Before this commit, we were effectively throttling to the number of
frames in the swapchain rather than on FRAME_LAG.
In the FIFO present mode, this could schedule too much work in the
presentation channel (since we …
> cube: Throttle rendering rather than presentation

- layers/core_validation.cpp
The condition tested in this check is only valid on platforms where
the swapchain dimensions must match the surface dimensions (e.g. Windows,
Xlib). In such cases, the surface *must* report minExtent == maxExtent ==
currentExtent, and this check would already be handled by the code directly
above the deleted check.
Platforms like Android allow the swapchain's imageExtent to be anywhere
within the surface minExtent/maxExtent range; if this does not match the
surface dimensions, it will be scaled accordingly.
> layers: Remove check for imageExtent == currentExtent

- layers/core_validation.cpp
Skip handling was inverted for this case. We ended up passing all the bogus pipelines to the driver.
> layers: Fix validation of compute pipelines

- layers/core_validation.cpp
- layers/swapchain.cpp
- layers/swapchain.h
- fix memory leak of `pQueueFamilyIndexSupport`
- remove vestige of queue family support check in the swapchain layer
> layers: Migrate surface support check to core_validation

- layers/threading.h
- tests/layer_validation_tests.cpp
This resolves GH #1712 by exempting VK_NULL_HANDLE from collision detection.
A new positive test confirms that the threading layer allows simultaneous use of VK_NULL_HANDLE.
> Handle VK_NULL_HANDLE in threading layer

- layers/core_validation.cpp
This case is covered better by the error messages from `DescriptorSet::ValidateDrawState`.
> layers: Remove unhelpful precheck in ValidateDrawState

- layers/descriptor_sets.cpp
- tests/layer_validation_tests.cpp
Fixes 1741
Immutable sampler descriptors are updated at create time.
Add test to verify that we don't warn when binding a descriptor set with just immutable sampler.
> Tobin gh1741 immut samp update

- layers/parameter_validation.cpp
- layers/parameter_validation_utils.h
- tests/layer_validation_tests.cpp
Received some reasonable feedback that the extra noise was unnecessary since this return code is perfectly valid, acceptable, and expected.  If anybody has requests to ignore other return codes, chime in here.
TLDR -- if `vkGetPhysicalDeviceImageFormatProperties`(), `vkGetPhysicalDeviceImageFormatProperties2KHR`() or `vkGetPhysicalDeviceExternalImageFormatPropertiesNV`() return "`VK_ERROR_FORMAT_NOT_SUPPORTED`", no log_msg call will be made.
> Suppress Errors/Warnings for GetPhysDevFormatProperties calls returning INVALID_FORMAT

- scripts/unique_objects_generator.py
The unique_objects_wrappers.h header was generated with code that
caused several compilation warnings.  This resolves those warnings.
Change-Id: I5ed3bdb6bbe7df48b3fe6fb6679916161b32fdfd
> layers: Fix unique_objects_wrappers.h

- tests/loader_validation_tests.cpp
Fix a few validation errors in the loader test which showed up
when validation is enabled.
Thanks to Tony for catching these.
NOTE: If you have an Nvidia and Intel in the system and Optimus
is enabled, you will get errors during the vkEnumerateDeviceGroupsKHX
test which appear to be because of the way Optimus is calling down
with a non-NULL invalid structure for the groups structure.
Change-Id: I808ca01c719a28f55ef3581647f598a4bdd9d18e
> WIP - tests: Fix loader test validation

- layers/core_validation.cpp
- layers/device_extensions.h
Update core validation to save the results of
vkGetPhysicalDeviceSurfaceCapabilities2KHR,
vkGetPhysicalDeviceSurfaceCapabilities2EXT, and
vkGetPhysicalDeviceSurfaceFormats2KHR so they can be used to validate
swapchain creation.
> layers: Record results from extension surface queries

- layers/core_validation.cpp
Fixes #1778. It is acceptable for the frameBuffer member of this structure to be NULL. Removed assert.
> Remove assert for NULL pInheritanceInfo->frameBuffer in BeginCommandBuffer

- tests/layer_validation_tests.cpp
Submit immediately followed by ResetCommandBuffer is nonsense. Sweeping
it under the rug doesn't make it any better; just use two command
buffers.
> tests: Remove bad behavior from QueueForwardProgressFenceWait

- layers/core_validation.cpp
- layers/core_validation_types.h
- tests/layer_validation_tests.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
Tidies up various bad behavior around invalidation & secondary command buffer in-flight accounting.
- The global inflight list is gone.
- Cascaded invalidation from resource -> secondary -> primary works
- Test quality improved
- secondary CB implicit or explicit reset causes invalidation of primary CBs (Fixes #1780)
> Better handle invalidation of primary CB due to secondary having been rerecorded

- layers/core_validation.cpp
- tests/layer_validation_tests.cpp
Consensus was that this warning was not helpful enough to overcome the noise it caused. Removed the check from CV and the corresponding test.
Fixes #1632.
> GH1632, Remove excess pClearValues warning

- layers/parameter_validation_utils.h
- tests/layer_validation_tests.cpp
Also implements the VkSamplerAddressMode variant in terms of the generic
variant, and adds a test to make sure that path is covered.
(Fixes #1770)
> layers: is_extension_added_token(VK_*_MAX_ENUM) returns false

- tests/layer_validation_tests.cpp
Way too much going on in this test, and no shared setup so easy to split.
Fix a bug introduced by Cort's recent change, and disable the final case until we figure out why it's not working on our arm64 targets.
> Split unrecognized value tests

- tests/layer_validation_tests.cpp
In our farm, we now get a clean assertion failure in the log rather than hanging displaying a dialog on a machine nobody is looking at.
> tests: Direct win32 CRT assertions to stderr rather than dialog

- tests/layer_validation_tests.cpp
This test was disabled in #1794, due to spurious failures on some test systems. This simplified version should avoid those failures.
> tests: Simplify and re-enable UnrecognizedValueMaxEnum

- loader/loader.c
Fix a few loader debug messages when an extension isn't valid.
The previous messages were confusing and didn't indicate what
was actually wrong.
Change-Id: Iccd0a4b2cfd673187cb7e92fe9cec23deb058ff2
> loader: Clean up a few messages

- loader/extension_manual.c
- loader/extension_manual.h
- scripts/loader_extension_generator.py
Add loader emulation for VK_KHR_get_surface_capabilities2 commands when one of two ICDs doesn't support the extension
> loader: Emulate VK_KHR_get_surface_capabilities2

- layers/parameter_validation.cpp
- layers/parameter_validation_utils.h
- scripts/parameter_validation_generator.py
Each API call is now checked for any extension dependencies and validates that they were all enabled.  These checks were moved from explicit checks in the cpp file to code-generated checks in parameter_validation.h.
Also added many missing/disabled calls to PV api-validation functions.
Fixes #1810.
Later we can add pNext chain extension dependency checks, and move device_extensions.h into codegen as well.
> Move Parameter Validation extension dependency checks into codegen

- loader/extension_manual.c
- loader/extension_manual.h
- scripts/loader_extension_generator.py
Add loader emulation for the following instance extensions:
- `VK_EXT_display_surface_counter`
- `VK_EXT_direct_mode_display`
- `VK_EXT_acqire_xlib_display`
The loader will still crash when calling `vkReleaseDisplayEXT` on an unsupported physical device, but this is legal since there's no way to acquire a display on the device without getting an error.
> loader: Add emulation for EXT inst extensions

- tests/layer_validation_tests.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
Reorganize layer/extension string handling in the test framework.
Make extension string vectors members of the framework base class, and
remove overloads that passed them as parameters. Added validation
of layers & extension immediately before CreateInstance/CreateDevice.
Added framework helper functions InstanceLayerSupported(),
InstanceExtensionSupported() and DeviceExtensionSupported() to
verify availablility of layer/extension names.
Modified positive test Maintenance1Tests as an example of how to
use for a device extension.
A whole-file clang-format turned up a lot of line-wrap changes, not 
related to the code I'd changed. Included here as a separate commit.
> Rework extension string handling in test framework

- layers/core_validation.cpp
- layers/shader_validation.cpp
- layers/shader_validation.h
Now we have no spirv details left in core_validation.cpp
> layers: Move validation of CreateShaderModule

- loader/loader.c
They may cause problems if the current codepage doesn't have them. For instance, in my case, VS issues a warning, and the warning is treated as an error.
> Replace characters “ and ” with "

- scripts/helper_file_generator.py
Generated extension helper has dependencies on vulkan.h and
utility (for std::pair) that weren't declared.
> scripts:Add includes to extension helper

- layers/object_tracker.cpp
This lived in the swapchain layer for some reason.  Added back into object tracker.
> Fix Doc Validator test: add in missing CreatDevice physical device object check

- layers/core_validation.cpp
This is a first pass at untangling validate & side effects in the query handling functions. I intend to replace all the maps keyed on `QueryObject` as a next step, which will allow us to go faster-- but correctness first!
> Various cleanup of query handling

- layers/core_validation.cpp
- layers/descriptor_sets.cpp
- layers/descriptor_sets.h
- tests/layer_validation_tests.cpp
DescriptorSetLayout data can be destroyed before any associated DescriptorSets.  Changed pointers-to-DSLayout-data to copies, at least for the time-being.
Also added a positive test for this case.
> Make DescriptorSetLayout data persistent for DescriptorSets

- layers/vk_validation_stats.py
- tests/_run_all_tests.ps1
- tests/_vkvalidatelayerdoc.ps1
- tests/run_all_tests.sh
- tests/vkvalidatelayerdoc.sh
- Added doc validator test back into windows run_all_tests script;
- Added 'terse_mode' parm to validator script;
- Modified test scripts to call validator script with terse_mode when called from the linux and windows run_all_tests scripts;
> Suppress info/warning messages when running doc validator from run_all scripts

- scripts/helper_file_generator.py
vk_extension_helper.h uses strcmp so add include of string.h to make
sure this dependency is correctly met.
> scripts:Include string.h in ext helper

- tests/_run_all_tests.ps1
- tests/run_all_tests.sh
Doc validation makes some directory assumptions that are fragile.
Temporarily disabling doc validation from run_all_tests scripts while
I figure out a better solution for how to organize the script and make
sure it can access all the files it needs.
> scripts:Temporarily disable doc validation

- BUILD.md
- loader/CMakeLists.txt
PR #1879 made it possible to build for 32-bit linux again, but the way you have to specify the 32-bit build doesn't fit cleanly with the environment variable method given in build.md. This PR lets you build by defining `export ASFLAGS=--32` on the command line, and updates the build instructions to specify that you now need to pass an assembler flag to the build.
> Enable linux 32-bit builds with ASFLAGS

- layers/buffer_validation.cpp
- layers/buffer_validation.h
- layers/core_validation.cpp
- layers/core_validation_types.h
Big change here is adjusting the CB state machine to no longer rely on last_cmd to distinguish two cases of `CB_INVALID`.
> Another round of housekeeping stuff

- tests/_run_all_tests.ps1
- tests/_vkvalidatelayerdoc.ps1
- tests/run_all_tests.sh
- tests/vkvalidatelayerdoc.sh
Fixes #1878
Re-enable doc validation in run_all_tests scripts but skip if directory 
structure does not align with expectations.
If vkvalidatelayerdoc script is not run from a directly two levels
below the layer source, then just skip running it. Print out a message
on how to run doc validation manually for those interested.
> scripts:Skip doc validation if src dir not found

- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/descriptor_sets.cpp
- layers/descriptor_sets.h
Clean up various shared_ptr uses for recent DescriptorSetLayout changes.
@chrisforbes, should be better but lemme know if I'm still missing anything
I looked at making AllocateDescriptorSetsData non-owning, but it's used to transfer shared_ptr ownership into DescriptorSet at create time so seemed appropriate to keep shared_ptr there although its lifetime is limited.
> Tobin shared ptr cleanup

- layers/parameter_validation.cpp
stride == maxStride should be valid, right?
> layers: test against maxVertexInputBindingStride should be >, not >=

- update_external_sources.bat
Update_external_sources could fail and the scripts that call it would continue using whatever external sources were already built.  This change makes the failure more obvious.
> build: Exit with return code in update_external bat

- layers/buffer_validation.cpp
- layers/buffer_validation.h
- layers/core_validation.cpp
The set of subresources touched by this submission is likely to be very
small compared to the complete set we're tracking. It doesn't make any
sense to copy this entire hashtable in each submit call.
Instead, maintain an overlay table with the submission's modifications
in it.
Saves approx 12s in an internal workload.
> layers: Don't copy all the image subresources every submit

- include/vulkan/vk_icd.h
- loader/LoaderAndLayerInterface.md
- loader/loader.c
- loader/loader.h
- loader/trampoline.c
Add a check to determine if the API version being requested can be
handled by the loader.  If it can't, then we return incompatible driver.
If we can, we continue along our merry way.
An addendum is that we also bumped the Loader/ICD interface version.
This was requested by Nvidia so that the ICDs know that we pay attention
to the version in the loader.  If they don't see the new Loader/ICD
interface version, they will handle the failing on all non-1.0 API
requests.
Change-Id: Icb7dd45e754c9f6a6c8186198333bacc68077b93
> loader: Add validation for apiVersion

- layers/core_validation.cpp
- layers/linux/VkLayer_core_validation.json
- layers/linux/VkLayer_object_tracker.json
- layers/linux/VkLayer_parameter_validation.json
- layers/object_tracker.cpp
- layers/parameter_validation.cpp
- layers/vk_layer_logging.h
- layers/windows/VkLayer_core_validation.json
- layers/windows/VkLayer_object_tracker.json
- layers/windows/VkLayer_parameter_validation.json
- tests/layer_validation_tests.cpp
Addresses GH issue #1880 and covers core validation, object tracker and parameter validation.  Also includes a test to verify that the name given to an object is referenced in an error message.
> layers: Add names to objects and print in validation

- layers/CMakeLists.txt
- scripts/parameter_validation_generator.py
Fixes #1922.  Added copy of this header file into the build directory.  @MaciejJesionowskiAMD, maybe can you give it a quick test on your setup?  And a big thanks to @karl-lunarg for adding an out-of-tree build check to our CI server.
> Fix out-of-tree builds

- layers/descriptor_sets.cpp
- layers/descriptor_sets.h
When checking IsCompatible() for a DescriptorSetLayout, the passed-in
layout is always from a pipelineLayout, however this was not specified
in the code. Add comment to specify this usage and update the error
message to always distinguish which of the layouts using in the compare
is from the pipelineLayout.
> layers:Identify layout from pipelineLayout

- layers/core_validation.cpp
- layers/core_validation_types.h
Refactoring CmdUpdateBuffer function to use the Pre/Post call pattern.
Updated the pre-path so that command buffer state pointer is const
throughout. Pulled the state update code into the post function.
Note that this slightly deviates from the previous pattern by doing
object state look-up in top-level function instead of passing a ptr to
a ptr to Pre* function and having it do the object state look-up.
I prefer this method as it allows const* throughout the Pre* call chain
and avoids the ptr derefs in Pre* function. I'm open to discussion if
others prefer the alternate method however.
> layers:Refactor CmdUpdateBuffer to Pre/Post

- layers/core_validation.cpp
This change arises from an issue reported by Alon at Samsung. He
reports that a driver bug is modifying the descriptor set state on
UpdateDescriptorSets() call, so the data is getting corrupted in
validation. Since UpdateDescriptorSets() is a void function, it
doesn't make a difference in validation if we update state before or
after the call, since the call itself won't change the state being
updated. It actually saves us a lock call to update pre-call.
> layers:Update descriptor state earlier

- loader/unknown_ext_chain_gas.asm
This addresses issue #1956, which complains that the loader is requesting an executable stack. See that issue for more details.
> loader: Remove executable stack from libvulkan.so

- scripts/helper_file_generator.py
- scripts/parameter_validation_generator.py
- scripts/unique_objects_generator.py
Replace all usages of the deprecated validextensionstructs member
attribute with the registry.validextensionstructs dict.  Internally the
registry builds this extension dictionary using the new structextends
type attribute.
> scripts: Switch codegen to use structextends

- layers/core_validation.cpp
- scripts/helper_file_generator.py
Fixes #1924.  Tacked a generated helper function onto the enum string helper header.
> Output strings instead of indices in physical device feature error messages

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/core_validation_types.h
- tests/layer_validation_tests.cpp
Fixes #1951 
This completes the explicit VUs for vkCmdPipelineBarrier().
Handling the secondary command buffer case and adding a new positive and negative test.
Handle secondary CB case by delaying validation when 2nd CB in renderPass doesn't have FB. Detect this case at CmdExecuteCommands() time and run validation there with the known FB.
> Tobin gh1951 secondary cb barriers

- layers/core_validation.cpp
Total nonsense like:
RECORDING -> INVALID_INCOMPLETE -> INVALID_COMPLETE
was possible when there were two invalidations.
> layers: Don't do bogus transitions in invalidateCommandBuffers

- tests/layer_validation_tests.cpp
Update CreateImageViewFormatFeatureMismatch test to make sure that the
desired DS format is supported before testing.
> tests:Check for D24_S8_UINT format support

- layers/core_validation.cpp
- tests/layer_validation_tests.cpp
Fixes #2020
Support from devs to remove this perf warning so just killing it.
Added a comment for future work where we can track which descriptors
are disturbed and reference that if a user attempts to use a
disturbed descriptor that isn't bound.
> layers:Remove distubed descriptor perf warning

- tests/layer_validation_tests.cpp
- tests/run_wrap_objects_tests.sh
Fixed CreateImageViewFormatMismatchUnrelated and CreateImageViewNoMutibleFormatBit tests. No longer fails on our test system.
> tests: Fix some LVL tests

- CMakeLists.txt
On some Linux distributions (e.g  openSUSE) the wayland headers are in
a subdirectory.
Adding WAYLAND_CLIENT_INCLUDE_DIR to include_directories in CMakeLists.txt
will fix this issue.
> CMake: GH1989, add wayland include dir to cmake

- CMakeLists.txt
- loader/CMakeLists.txt
- loader/LoaderAndLayerInterface.md
- loader/loader.c
- loader/vk_loader_platform.h
Previously, we added a change that allows ICDs to be specified through the PnP system. This PR extends that to also allow layers to be specified through the same means. This is needed so that ICDs can continue to install layers in future versions of Windows, where they will not be able to access the old paths. The old paths are retained, and are expected to be used by anything that's not a driver.
This change also extends the PnP registries to allow a `REG_MULTI_SZ`, in the case that multiple layers or ICDs need to be specified from a single device.
> Handle layers in PnP registry locations

- layers/core_validation.cpp
- layers/core_validation_types.h
Fixes #2070 
Pipeline can outlive the renderPass that it's created with so add
shared_ptr to RENDER_PASS_STATE to PIPELINE_STATE to make sure
renderPass is available for the life of the pipeline.
> layers:Pipe state owns render pass ptr

- layers/descriptor_sets.cpp
The previous condition was always false.
> layers: Correctly check if descriptor was updated

- layers/core_validation.cpp
The `boundDescriptorSets` vector may be resized in `PreCallRecordCmdBindDescriptorSets()`.
> layers: Avoid potential NULL pointer dereference

- scripts/vk_validation_stats.py
- tests/vkvalidatelayerdoc.sh
vk.xml now includes some wacky unicode characters which end up in the vk_validation_error_database.txt and cause the doc validator to choke.  Added UTF encoding to fix that, and added python3 to the validator script to fix _that_.
> Fix doc validator on Windows

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/core_validation_types.h
- tests/layer_validation_tests.cpp
Refactoring updates split out from https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/2103
- Pre/post refactoring for QueueBindSparse, AcquireNextImageKHR
- Add caller name to ValidateObjectNotInUse
> Core validation refactoring

- loader/loader.c
loaderGetDeviceRegistryEntry() out of memory result was not handled properly.
> Loader: Fix OOM in loaderGetDeviceRegistryFiles()

- demos/vulkaninfo.c
Removed messages marked with the "INFO" tag from vuklaninfo.
> vulkaninfo: Remove "INFO" messages

- demos/cube.c
- demos/cube.cpp
The physical display rendering code didn't compile due to drift in `vulcan.hpp`. Update for these changes.
Tested on i.MX8M / Vivante GC7000L.
(same change is needed in https://github.com/LunarG/VulkanSamples, originally noticed it there)
> demos: Update cube.cpp DISPLAY_KHR code

- loader/vulkan.pc.in
GH 2121,
Specify the Private Libs to "Libs.private" in the vulkan.pc.in cmake config file.
> loader: GH2121; move private libs in vulkan.pc file

- layers/core_validation.cpp
- layers/core_validation_types.h
Only self-dependencies permit barriers within the renderpass, so we
don't want any other dependencies here.
Fixes #2123
> layers: Only include self-dependencies in subpass->dep index

- BUILD.md
- build-android/cmake/layerlib/CMakeLists.txt
- build-android/jni/Android.mk
- build-android/jni/Application.mk
- build-android/update_external_sources_android.bat
- build-android/update_external_sources_android.sh
This updates the android build to align it with the android NDK build.
That will make it simpler to keep validation layers in the NDK build more up to date.
It also allows use of github validation source in combination with the NDK source version of shaderc and SPIRV repositories.
> Stroyan android build

- layers/core_validation.cpp
- layers/core_validation.h
- layers/core_validation_types.h
- tests/layer_validation_tests.cpp
Track when a semaphore payload is imported and restored, turn off
semaphore validation when using an external payload.
VK_KHR_external_semaphore_fd entry points and test cases to come in a follow-on patch
> External semaphore compatibility fixes

- tests/run_wrap_objects_tests.sh
Replace blacklist with shorter whitelist -- as there are fundamental incompatibilities between this test and using the device profile layer, it was too easy to add a new validation test without updating the blacklist (not to mention being completely non-obvious).  This replaces the blacklist with a much shorter whitelist of stable tests, which should still serve to validate the loader's ability to handle wrapped instance objects.  And, it makes the test much faster.
> Change wrap-objects loader test filter

- demos/vulkaninfo.c
Some formats were shown as unknown in vulkaninfo's list, make sure they're all included.
> demos: VkFormatString add missing formats

- layers/core_validation.cpp
- layers/core_validation_types.h
- tests/layer_validation_tests.cpp
- tests/vktestbinding.cpp
- tests/vktestbinding.h
Fixes GH issue #2096 / LX issue [712](https://vulkan.lunarg.com/issue/view/59b6b9b2e46ffe6c0d3db481)
Treat imported external memory as valid (similar to mapped memory) so we don't warn when an image or buffer bound to the external memory is used as a src.
> Remove uninitialized warning for external memory

- layers/unique_objects.cpp
Helper routine was being called outside the lock causing freezes in Dota2.
> Move BuildTemplate call inside global lock

- layers/object_tracker.h
- layers/object_tracker_utils.cpp
- scripts/helper_file_generator.py
Fixes #2097.  
Devices were tracked as part of the device data itself and were not processed correctly when an instance was destroyed.  Made devices child objects of instances, added explicit destruction, and improved the way device objects are validated.  
A related fix takes care of some off-by-one issues in the object-type-helper code-gen discovered during debugging.
> Improve Device Object Tracking

- layers/core_validation.cpp
Slight tweak to previous warning so that it only fires if renderPass is valid. This prevents warning for random data due to uninitialized buffer (unless random data aliases valid renderPass which is unlikely and doesn't hurt to warn on).
Only warn if a secondary command buffer has a renderPass that is valid
and has not set VK_COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT. This
avoid warning for the case where uninitialized data is present in the
renderPass handle.
> layers:Limit warning on secondary command buffer

- layers/parameter_validation_utils.cpp
- scripts/helper_file_generator.py
- tests/layer_validation_tests.cpp
Remove all usages of constexpr to restore compatibility with Visual Studio
2013.  Also make a handful of other minor edits where the VS2013
compiler was reporting errors.
> VS2013 compatibility

- tests/layer_validation_tests.cpp
Three cases were disabling DS attachment to accomodate a driver bug,
but this is actually invalid for the tests.
Re-enabling the DS attachment for those cases as with device updates
and other workarounds, the tests are now working across all devices.
> tests:Re-enable DS attachment for TriTest

- layers/buffer_validation.cpp
- tests/layer_validation_tests.cpp
Modified positive test UncompressedToCompressedImageCopy to provoke
the issue reported in GH 2239
Fixed destination extents calculations in buffer_validation.cpp to
avoid the erroneous errors.
(Apologies for the noisy "regions[i]->region" rename.)
> layers: Repro and fix GH 2239

- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/parameter_validation.h
- layers/parameter_validation_utils.cpp
- layers/shader_validation.cpp
- layers/unique_objects.cpp
- layers/unique_objects.h
- scripts/helper_file_generator.py
- scripts/parameter_validation_generator.py
- scripts/unique_objects_generator.py
- tests/layer_validation_tests.cpp
Some `VkGraphicsPipelineCreateInfo` pointers must be ignored under some conditions,
but were not in the layers (resulting in crashes despite valid use).
> layers: Fix Graphics Pipeline pointers not ignored

- .travis.yml
- scripts/check_code_format.sh
Check modified lines in a pull request for correct clang-format.
Note that checking is not performed unless there is a pull request.
Heavily leveraged from https://github.com/KhronosGroup/SPIRV-Tools.
> build: Add clang-format checking of pull request changes to CI

- tests/layer_validation_tests.cpp
The ExternalMemory test is a positive test that would only pass if
underlying device functionality was verified.
Remove the functional check as that is not appropriate for LVL tests.
The purpose of positive tests in LVL is to stress the validation layers
in specific cases that are known to have had bugs or have potential for
bugs. These tests shouldn't be validating underlying device
capabilities. CTS is the appropriate place for device functional tests.
> tests:Remove functional check from ExternalMemory

- tests/CMakeLists.txt
The tr1 namespace is used by Google Test and has been deprecated
starting with Visual Studio 15.5.  Turn off the deprecation warning
until we can update Google Test to prevent the build from failing.
> Turn off tr1 namespace deprecation warning

- scripts/object_tracker_generator.py
This makes it more easy to locate a header in configs which have the
CWD set to something less obvious. In Chrome's case the build directory
is completely separated from the script directory.
Also reset the CWD after the header is found to keep the build intact.
This is similar to the change to the parameter validation generator.
@tobine PTAL, missed this in the object tracker script when I was fixing the parameter validation script.
> scripts: Scan CWD in object tracker generator.

- .travis.yml
- build-android/jni/shaderc/Application.mk
We're unable to complete test runs using r16b, and being short staffed for the holidays, switching back to an earlier release that is working.  We'll get it sorted out once everyone is back.  We've already switched the test farms to r15c.
> Roll back to NDK r15c

- scripts/external_revision_generator.py
This fixes the external revision generator script to first try to
use 'git', then fall back to 'git.bat' if the first invocation throws
a WindowsError.
@tobine PTAL
> layers: Fix git.bat fallback on Windows.

- scripts/determine_vs_version.py
With VS 2017 MS decided to change the version output of MSBuild so that it now includes e.g. an Umlaut for the german version:
Microsoft (R)-Buildmodul, Version 15.5.179.9764 für .NET Framework
This causes the ```determine_vs_version.py``` script to fail with a decoding error (on Python 3.6 at least):
Traceback (most recent call last):
File "determine_vs_version.py", line 78, in <module>
sysCallOut = os.popen(versionCall).read()
File "C:\Users\Sascha\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 49: character maps to <undefined>
As such no proper VS Version is detected and the scripts relying on this will fail (like …
> Fix for VS version detection decoding error on international locales (VS 2017)

- layers/shader_validation.cpp
- tests/layer_validation_tests.cpp
The shader capability required-feature/extension checks assumed a unique mapping from any single capability ID to a single feature or extension. SPIRV recently added capability **ShaderViewportIndexLayerEXT** which shares the same ID (5254) as **ShaderViewportIndexLayerNV**, but requires a different extension name (_SPV_EXT_shader_viewport_index_layer_, vs _SPV_NV_viewport_array2_).
This PR modifies capability checks from "must have" to "must have at least one of" logic for cases where there are multiple mappings of capability IDs.  It would be better if we could infer exactly _which one_ of the feature/extensions the shader requires, but that doesn't seem possible to know from the SPIRV binary alone.
Resolves issue #2288.
> Allow non-unique shader capability mappings

- build-android/jni/Application.mk
This option is not required if all components are to be built. Removing this will make VulkanTools trunk merges safer and easier.
> Remove APP_MODULES from Android Application.mk file

- BUILD.md
- include/vulkan/vk_sdk_platform.h
- layers/core_validation.h
- layers/core_validation_types.h
- layers/descriptor_sets.h
- tests/test_environment.cpp
- tests/vkrenderframework.h
- tests/vktestbinding.cpp
- tests/vktestbinding.h
- tests/vktestframework.h
- tests/vktestframeworkandroid.h
Restore compatibility with Visual Studio 2013:
- Put noexcept specifier behind a common macro
- Provide move constructors and assignment operators because we cannot rely on the compiler to generate them
- Update BUILD.md to list VS2013 as supported again
TODO:
- Update AppVeyor configuration to run VS2013 -- in progress
> VS2013 Compatibility Round 2

- scripts/mock_icd_generator.py
Move include <string> to header file to fix
clang build when using libstdc++.
Fixes #2303
Change-Id: Id2fc97be7cb83fa12ee1495ef57177c0a7dad893
> icd: Move include to header to fix clang build

- layers/CMakeLists.txt
Fixes #2316
Affects only Windows builds.
Need to compile code that generates large object files
with the /bigobj option in order to avoid exceeding the
default number of sections in an object file.
This change applies the /bigobj compiler option to all
configurations, rather than just Debug.
It also applies it only to selected files, instead of
all the files in the project.
Although /bigobj is now applied to Release builds,
this does not increase build time.
> build: Fix application of /bigobj compile flag

- scripts/mock_icd_generator.py
Calling tests use return values from GetImageSubresourceLayout to
compute offsets in texures.  Zero'd values are safe for this usage and
add minimal overhead to icd.
Change-Id: If52cf240925d2f7a41bb22d87519a918be5eb60a
> Fix two test crashes on Windows with mock_icd enabled

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/descriptor_sets.cpp
- layers/descriptor_sets.h
Cleans up descriptor set validation, by replacing iterative lookups with O(log n), reorganizing data to avoid duplicate lookups, and tracking already validated state (cached validation) -- particularly with an eye toward improving performance for large numbers of descriptors bound. Addresses #2221 
In testing, factors of 3-10 reduction in frame times were observed for use cases with "many" descriptors.
> Performance fixes for large numbers of bound descriptors -- fixes #2221

- layers/unique_objects.cpp
- scripts/helper_file_generator.py
- scripts/unique_objects_generator.py
These were previously generated in unique objects and used for the extension white-list.  The same information will be needed in other layers, so moved this definition to a common header file and updated U-O to use the new definitions.
> Add device/instance extension lists to extension helper header file

- .appveyor.yml
- build_windows_targets.bat
- update_external_sources.bat
Add options (--debug --release --32 --64) to the
update_external_sources.bat script so that it can
be used to build external libraries for only the
desired platform/configuration combinations.
This helps the AppVeyor CI builds by building only
the platform/configuration combination needed for the
current job.
> build: Improve update ext srcs script for better CI

- include/vulkan/vk_layer.h
- loader/LoaderAndLayerInterface.md
- loader/loader.c
- loader/loader.h
- loader/trampoline.c
- scripts/loader_extension_generator.py
Currently, layers cannot intercept functions that are called without an instance (`vkEnumerateInstanceExtensionProperties` and `vkEnumerateInstanceLayerProperties`). However, it can be useful for layers to intercept these functions. For example, the devsim layer @mikew-lunarg has in the VulkanTools repo needs to filter out extensions if it is to properly simulate devices.
This PR adds a new mechanism so that layers can intercept these calls. Only implicit layers can do this, since explicit layers are supposed to be explicitly enabled at instance creation while implicit layers are enabled externally before the program runs. A new mechanism to intercept the layers is needed because the current mechanism passes the information during instance creation, and relies on using the pNext chain in …
> loader: Allow layer to intercept commands before instance creation

- layers/core_validation.cpp
Addresses crashes in validation forcertain sparse memory CTS testing.
Added nullptr check to BindBufferMemory and BindImageMemory validation
to cope with invalid memory arguments (reported elsewhere).
Change-Id: I52266490ccfe9eff7d5f451cddc4d3bbf94b3c5d
> layers: Make bind more robust to invalid memory

- loader/loader.c
- loader/loader.h
- loader/trampoline.c
- loader/vk_loader_platform.h
When unloading the vulkan loader dynamic library, a couple of mutexes were not getting cleaned up. This PR adds a mechanism to clean them up.
This PR addresses issue #2341.
> loader: Clean up mutexes on destruction

- scripts/vk_validation_stats.py
The check for required files was counting the files multiple times (when multiple build/dbuild/et.al. were present) and aborting silently.  The check now correct counts files and exits with non-zero exit code on failure.
> layers: Fix doc validation file list check

- loader/loader.c
- loader/vk_loader_platform.h
This PR addresses issue #2315.
This resolves a bug where it was impossible to enable an extension that was defined in a layer if that layer was not passed by the application. This applied to implicit layers, explicit layers enabled by environment variables, and metalayers.
> loader: Fix enabling extensions from layers

- loader/CMakeLists.txt
- loader/loader.c
- loader/loader.h
- loader/trampoline.c
- loader/vk_loader_platform.h
This PR fixes #2355. It fixes the bug where the loader's global initialization was being skipped when the loader is built as a static library on windows
> loader: Fix static library initialization

- tests/layer_validation_tests.cpp
- tests/vktestbinding.h
Cleaned up DSUsageBitsError, using the framework calls to reduce boilerplate code to improve maintainability and readability.  Added helper calls as needed.  Addresses (fixes?) #2184
> Clean up/use framework in DSUsageBitsErrors

- CMakeLists.txt
Some CI systems were insisting this was a good idea.
> Fix glslang validator cmake hint path

- demos/smoke/CMakeLists.txt
Demo change led to this test's binaries being output to the incorrect location.
> Fix output location of smoketest

- layers/vk_layer_config.cpp
- layers/vk_layer_config.h
Required for hassle-free linking to layer_utils lib.
> Add LAYER_EXPORT specifiers to vk_layer_config

- tests/layer_validation_tests.cpp
- Swap the roles of the two renderpasses to avoid CmdBeginRenderPass
complaining about mismatches between framebuffer and rp
- Get rid of spurious input attachment which caused extra error
messages. If the input attachment case is interesting, we should test
for it separately. The rest of this test only cares about a format
difference between the renderpasses.
> tests: Fix various issues in VkLayerTest.IncompatibleRenderPass

- CMakeLists.txt
- icd/CMakeLists.txt
- layers/CMakeLists.txt
- loader/CMakeLists.txt
- tests/CMakeLists.txt
- tests/layers/CMakeLists.txt
This sets up cmake to locate the temporary or worker MSVC projects into a subfolder called lvl_cmake_targets. This simply unclutters tte Visual Studio Solution Explorer projects pane, and does not affect functionality.
For example, all of the solution explorer projects such as *-def-file, *-json, and the file generator targets will show up in the lvl_cmake_targets folder.
> Move LVL temporary & worker MSVC cmake targets into solution explorer subfolder

- layers/vk_layer_logging.h
This file was often included in files where only a subset of the functions were called, resulting in -Wunused_function warnings from GCC. Made these functions inline to avoid the warnings.
> Avoid warnings in vk_layer_logging.h

- loader/loader.c
Fix a bug where having a json file in the layer path that isn't a valid layer would cause the other valid layers to be skipped. This fixes #2403.
> loader: Fix loader skipping layer files

- layers/buffer_validation.cpp
One other minor fix-up. Spelling error noticed by @cnorthrop . Fixing spelling also triggered clang-format to kill a line, so win-win.
> layers:Fix spelling truely->truly

- layers/core_validation.cpp
- layers/core_validation_types.h
Some very simple additions for tracking image sparse memory binding.
This only adds a few new warnings intended to help enforce correctly query of sparse requirements and correct binding of sparse metadata.
This is intended to be a rough start for future development, intended to help with some low-hanging issues that @chrisforbes flagged as a good focus in developing CTS tests. It adds some new intercepts and state tracking for sparse images.
Note that when performing git-fu to rework CLs I accidentally pulled the decl of image_states set into 3rd commit but its not used until 4th commit.
> Tobin sparse metadata check

- demos/vulkaninfo.c
Two additional vulkaninfo output modes.
Possible output modes:
1. Std console (human readable) only
2. Html only
3. **Json only**
4. **Html AND json**
Json specified with `-j`, `--json`, or `--json=1` (to specify which gpu to target on a multi-gpu system).
> Vulkaninfo json generation for use with DevSim

- layers/shader_validation.cpp
Present-but-broken stages need to still be considered present for
the purposes of walking `producer` forward. Otherwise a broken GS will
for example cause us to get confused and try to match the VS interface
against the FS.
Bug: #1600, others.
> layers: Fix validation of shader pipelines when a stage is broken

- .travis.yml
- layers/core_validation.cpp
- tests/layer_validation_tests.cpp
Fixes #2431 -- We hit this issue independently yesterday. 
Descriptors are not intended to count multiple times against the
maxDescriptorSet* limits if they are accessible from multiple stages.
Required adjusting various subtests in CreatePipelineLayout*.
Also fixed some related issues in those tests:
- Input attachments are ONLY accessible to the fragment stage.
- Various assumptions about divisibility of the maxDescriptorSet* limits
There are still many robustness issues in these tests -- it appears we
don't hit them with real implementations, but still wrong.
> layers: Fix miscounting of descriptors for multiple stages

- .gitattributes
Git settings caused shell scripts to get converted to carriage-return line endings -- changed this to a line feed line ending (which lets the scripts run in Cygwin shells on Windows).
> Modify .gitattributes for unix line endings on shell scripts

- layers/buffer_validation.cpp
- layers/buffer_validation.h
- layers/core_validation.cpp
Fixes a bug in image layout state handling that appeared with
khr_maintenance1. When a 3D image which was created with the
VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT_KHR flag is transitioned
between layouts, we now also record a transition for each depth
slice, treating it as an array layer subresource.
The actual fix is just two lines within TransitionImageLayouts().
Also included are some debug-enabling refactoring to distinguish
layout state updates vs additions, and support for new aspect
mask bits.
Fixes #2408 
Fixes #2210 
Fixes #1650 
Change-Id: Ibb5131a6dba8fcdeafe5e6d94af2decf751842ec
> Fix 2408: record 3D image-slice layouts as subresources

- demos/vulkaninfo.c
Rerouted error messages from stdout to stderr.
Regular, human readable output and json output both print to stdout (depending which is specified) but error messages sent to stdout when generating json result in invalid json output.
> demos: Redirect error messages to stderr

- layers/unique_objects.cpp
- layers/unique_objects.h
- scripts/unique_objects_generator.py
As new extensions are developed, objects created through instance-level APIs are increasingly referenced by device-level APIs.  Currently, these are artificially separated into separate unique_id maps for each instance and device layer data object.  Made unique ID map global, with the single map shared across all instances and devices.
> Move to a single unique_objects ID map

- loader/vk_loader_platform.h
MSVC allows implicit conversion from function pointers to void*.
The C++ standard doesn't allow this, and clang-cl emits a warning
when this is done.  This change fixes these warnings in
Vulkan-LoaderAndValidationLayers.
Arguably, loader_platform_get_proc_address() should return a
FARPROC so that the compiler can help checking calling conventions,
but this is the simplest fix that unblocks us.
This is needed for https://crbug.com/550065
> build: Fix -Wmicrosoft-cast warnings with clang-cl

- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/descriptor_sets.cpp
- layers/descriptor_sets.h
- layers/hash_util.h
- layers/hash_vk_types.h
- layers/shader_validation.cpp
Fixes #2214 .  Upgrades the pipeline layout compatibility and recording to (IIAC) match the compatibility text of of the spec.  Push constant and 1-N comparisons for compatibility are added for each set in the current layout.  Set update/disturb logic is now shared with push descriptors. 
As compatibility validation is deep nests (for each Set N { foreach set 1 through N } {for each set { for each binding in set }, where the inner three loops are comparing invariant quantities, the compatibility check has been reduced to a comparison of unique ID's which integrate each inner loop in  "canonical" definitions stored in dictionaries.  The dictionaries share a common container type and used the standard overload mechanism for std::equal_to and std::hash.
Specific layer state data (where …
> Adds push constant range and "compatible for set N" logic to pipeline layout compatibility validation and recording

- layers/buffer_validation.cpp
- layers/parameter_validation_utils.cpp
- tests/layer_validation_tests.cpp
Updates parameter validation checks to recognize as legal the new aspect flag bits (_VK_IMAGE_ASPECT_PLANE_n_BIT_KHR_) added by the **VK_KHR_sampler_ycbcr_conversion** extension, and avoids a couple false positive core validation errors when calling CmdCopyImage on a multiplane image. Adds a positive test of CmdCopyImage using a multiplane image.
This PR avoids the false positive errors generated by existing validation code.  A follow-on PR will add the new multiplane VUs.
Fixes: #2378.
> Parameter validation checks recognize multiplane aspect bits

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/core_validation_types.h
- tests/layer_validation_tests.cpp
Add check at CmdExecuteCommands() time to make sure that rects from CmdClearAttachments() are within the bounds of renderArea for active renderPass.
Overloaded the existing vector of lamba functions to account for this use case.
Updated existing positive test so it hit a bit more code, and added new negative test to verify new error is correctly triggered.
> Tobin gh2480 clear attach 2nd cbs

- layers/descriptor_sets.cpp
- tests/layer_validation_tests.cpp
Fill validation hole where we didn't verify that a descriptor's sampler was valid at draw time. Add test to hit this case.
> Tobin gh2486 dangling sampler

- layers/core_validation.cpp
Transfer queue is called out but was omitted. Verified all other Cmd queue flag cases as well.
> Fix queue bits for CmdWriteTimeStamp

- layers/core_validation.cpp
In core validation layer's DestroyCommandPool API entry function, the
ext layer's API call is executed outside of the lock, and before the
command pool's command buffers are erased from the layer's command
buffer map. That means that between next layer's call and the time the
lock is regained, any other thread can allocate other command buffers.
In particular, it may reuse the memory freed the command, and then the
core validation layer will not insert a new entry in the command buffer
map. So after the lock in regained and the command pool's command
buffers are erased from the map, leaving those allocated with no state,
leading to either crashes or assertions later on. The fix is to move the
release of command buffers before releasing the lock the first, before
calling the next layer's …
> layers: Fix command buffer allocation ABA bug (issue #2517)

- icd/CMakeLists.txt
- tests/layers/CMakeLists.txt
Put icd and test layer json files in ```$<CONFIG>``` directory when using
Xcode generator so layer tests can be executed and debugged from within
Xcode.
Side note: I think all of the CMake script we have to wrangle json files can be greatly simplified but this PR reuses existing patterns instead.
> tests: macOS CMake fixes for Xcode generator

- layers/buffer_validation.cpp
- layers/buffer_validation.h
- layers/core_validation.cpp
- layers/core_validation_types.h
- tests/layer_validation_tests.cpp
- tests/vkrenderframework.cpp
- tests/vkrenderframework.h
- tests/vktestbinding.cpp
- tests/vktestbinding.h
Two classes of false positives are address
1) Incorrectly validated src(dst)StageMask on acquire(release) operations
2) doubly accounting image layout transitions during release/acquire barrier pairs (from @chrisforbes)
This is done by detecting the type of barrier operations and gating validation based on they operation type.  For 1) this is at command granularity, for 2) at barrier granularity
In order to add tests, the vk_testing and Vk*Obj framework was enhanced w.r.t. queue and command buffer, while maintaining (with one, small, addressed exception) interface compatibility.
Addresses issues: #1986, #1550, #865, #2522
> Eliminate false positives in queue family ownership transitions / add positive tests

- layers/threading.h
Update threading layer non-dispatchable type handling to reflect updates
to the vulkan header for Linux/x32 memory model support.  Includes new
static asserts to detect future mismatches.
This in response to [Pull Request 2484](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/2484) -- as the original poster does not have a signed CLA.  The updated #define logic is copied *not* from 2484, but from vulkan_core.h, and then clang formatted.
As I don't have access to x32 systems pinging the author of 2484.
Tagging @cnorthrop to ensure no Android issues. (e.g. does Android support Arm/ILP32 or do some other VK_DEFINE_NON_DISPATCHABLE_HANDLE magic that we'd need to be aware of?)
> layers: Correct non-dispatchable type handling

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/descriptor_sets.cpp
- layers/object_tracker.h
- layers/object_tracker_utils.cpp
- layers/parameter_validation.h
- layers/parameter_validation_utils.cpp
- layers/shader_validation.cpp
- layers/threading.h
- layers/unique_objects.cpp
- layers/vk_layer_logging.h
- scripts/parameter_validation_generator.py
Changed log_msg():
- Automatically append the relevant spec text to the log_msg text, no longer requiring it to be manually inserted.
- Deleted 'location' variable from log_msg calls
- Deleted 'layer prefix' variable from log_msg calls
Before:
```
log_msg(dev_data->report_data,
VK_DEBUG_REPORT_ERROR_BIT_EXT,
VK_DEBUG_REPORT_OBJECT_TYPE_IMAGE_EXT,
handle,
__LINE__,
error_code,
"MEM",
"Object used with no memory bound. Memory should be bound by calling vkBindImageMemory(). %s",
validation_error_map[error_code]);
```
After:
````
log_msg(dev_data->report_data,
VK_DEBUG_REPORT_ERROR_BIT_EXT,
VK_DEBUG_REPORT_OBJECT_TYPE_IMAGE_EXT,
handle,
error_code,
"Object used with no memory bound. Memory should be bound by calling vkBindImageMemory().");
````
> Prep for text vuids: log_msg improvements

- demos/cube.frag
- demos/cube.vert
This has been bugging me forever. Added some minimal n-dot-L screen-space lighting to the cube/cubepp samples' shaders.  glsl shader code changes only.
Unlit
n-dot-L Lighting
> Add some simple cube lighting

- layers/buffer_validation.cpp
- layers/vk_format_utils.h
The FormatIsColor() util fxn classified anything not depth or stencil as 'color', and applied the aspect bit checks correspondingly. This PR segregates multi-plane formats from the catch-all color classification and adds multi-plane specific aspect bit checks for them.
Resolves #2527.
> Fix multi-plane aspect bit check

- layers/buffer_validation.cpp
There is a case (memory barrier) where a multiplane image can have
the color aspect bit set, so the general aspect check should allow
it. In the common case where only VK_IMAGE_ASPECT_PLANE_n_BIT
bits are allowed, there are specific VUIDs in place to enforce.
This fixes an "unexpected error" result that recently appeared for
the CopyImageMultiplaneAspectBits test.
Change-Id: I766da2940955d8a7b72ec26e4dbefe9e60eb0b08
> Accept color aspect bit for multiplane image

- layers/descriptor_sets.cpp
- tests/layer_validation_tests.cpp
Includes fixing a corresponding typo in a descriptor_sets log_msg call.
> Correct typos/spelling in layer_validation_tests

- scripts/mock_icd_generator.py
Add mock ICD support for vkGetPhysicalDeviceSurfacePresentModesKHR and
vkGetPhysicalDeviceSurfaceFormats[2]KHR.
> icd:Add new physical device query funcs to ICD

- layers/buffer_validation.cpp
- layers/descriptor_sets.cpp
The simple "// fall through" comment causes the compiler to omit a
warning.
> layers:Update comments to avoid compiler warnings

- layers/buffer_validation.cpp
- tests/layer_validation_tests.cpp
Fixes #2587 
Lambda needs to capture rect by value, not the ptr to VkClearRect, which may have its underlying rect changed.
> Tobin gh2587 2nd cb clear attach fix

- loader/loader.c
Clarify several loader warnings about layers so that they include
the name of the layer that is causing an issue.
Change-Id: Ie48d73f6cc8466c3114597831fef451b3ab32bf7
> loader: Clarify loader warning

- demos/vulkaninfo.c
vkGetDeviceGroupPresentCapabilitiesKHR requires VK_KHR_SURFACE and VK_KHR_SWAPCHAIN
in addition to VK_KHR_DEVICE_GROUP
> demos: Enable all required exts for present caps

- scripts/spec.py
When the surrounding asciidoctor conditionals of a VUID change it may
impact validation even if the VUID text does not change.  Detect this in
spec.py and flag for manual intervention.
Change-Id: Idf802955ba9bbfe911edd4114fb28bdddf5fcc9b
> scripts: Add spec.py check for ext changes

- loader/loader.c
Fix a bug where when mixing a 1.0 and a 1.1 driver, if the loader
stores the 1.0 driver first, the apiVersion field in vkCreateInstance
will be rewritten to 1.0 for both drivers. Now it will only be
changed for the 1.0 driver, as intended.
Change-Id: I9e7c5e0b0b7c0eb660082319dcddd9e8ef8adc61
> loader: Fix a 1.0/1.1 versioning bug

- tests/layer_validation_tests.cpp
This test has been crashing in some versions of Linux nvidia drivers.
Crash occurs in vkCreateGraphicsPipelines.
works: 375.27.14
fails: 387.42.03
This test sets rasterizerDiscardEnable to true as part of creating
a graphics pipeline. Setting it to false allows the test to pass.
The test also passes if no fragment shader is provided for the pipeline.
Several other tests set rasterizerDiscardEnable to true, but they
do not crash since they are negative tests and the call to
vkCreateGraphicsPipelines probably doesn't make it to the driver.
There's one other positive test that sets rasterizerDiscardEnable
to true, but it doesn't supply a fragment shader.
Since whether a crash occurs or not depends on the driver version
and because turning on discard isn't part of the test's goals, it
seems …
> tests: Workaround crash in PSOPolygonModeValid

- layers/core_validation.cpp
Validation for VkQueueBindSparse would previously cause null pointer dereference because the count of image binds was used to index into the opaque image binds list rather than the image binds list.
>  Image bind count is associated with pImageBinds rather than opaque binds

- demos/vulkaninfo.c
Changes consist of reordering print statements for all paths of output (human_readable, html, and json) and the addition of employing the qsort function (and new comparison functions) to reorder global layers and extension properties in the app instance.
Please let me know if you think I've sorted sections of output that maybe shouldn't be sorted.
Sections left unsorted because the current ordering seems to make the most sense: Presentable Surfaces, VkQueueFamilyProperties, and Format Properties
Change-Id: I075a6897c3070f70d7073c22e7100c49c19073a3
> demos: Sort most vkinfo output alphanumerically

- scripts/helper_file_generator.py
Addressing #2613 : add three missing promoted extensions to promoted extension lists in code generation for device and instance initialization.
> Add missing promoted extensions to instance and device initialization

- layers/CMakeLists.txt
Hi,
I think the layers files should be installed in the data root directory. They are not configuration files, so they do not belong in /etc. Please review,
Sarnex
> Make the layers install into the data root directory

- layers/vk_layer_logging.h
Change debug log message to use correct VkObjectType to
VkDebugReportObjectTypeEXT method, avoiding the index out-of-bounds
lookup that caused a SEGV.
Fixes [LunarXchange 764](https://vulkan.lunarg.com/issue/view/5ae8941ae46ffe13892f3e96)
Change-Id: Ibb6e485eccb36ff0e9b49f0722d8f2d0bf660982
> layers: Fix segv during DebugReportCallback setup

- layers/buffer_validation.cpp
- layers/core_validation.cpp
- layers/core_validation_types.h
- layers/descriptor_sets.cpp
Implementation was incomplete -- when broken it produced incorrect warnings and when working produced non-specified warnings.  If this has a place in the future, it's in the assistant layer.
Fixes #2616.
> Remove Fill Memory warnings

- layers/object_tracker_utils.cpp
- scripts/object_tracker_generator.py
Resolves #2597.
Add VkDisplayKHR and VkDisplayModeKHR tracking to
VK_LAYER_LUNARG_object_tracker for vkGetPhysicalDeviceDisplayPropertiesKHR() and vkGetDisplayModePropertiesKHR().
> layers: Track display and display mode objects

- layers/buffer_validation.cpp
- tests/layer_validation_tests.cpp
Fixed a validation bug that produced a false positive when a multiplane image is created with VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT flag, but the imageview format is identical to the image format.
Added the repro case to existing validation test.
Fixes #2619.
> Fix a multiplane imageview bug

- tests/device_profiles/geforce_940m.json
- tests/layer_validation_tests.cpp
Simplified this test by using VkImageObj in place of direct vulkan
calls. Additionally added a fake multiplane image format to the geforce
940m device profile so that this repo would have a device profile that
doesn't skip this test.
> tests: Clean up multiplane view format test

- layers/core_validation.cpp
- layers/core_validation.h
- scripts/mock_icd_generator.py
This is related to #2670 but not exactly a fix.
A couple of updates to prepare core validation for handling GPDF2 extended struct. Not checking any extension structs yet but getting things ready for that with some more changes.
Added mock GPDP2 support for VkPhysicalDeviceDescriptorIndexingPropertiesEXT struct.
> Tobin gpdf2 support
