layers/core_validation.cpp

This is the first step toward moving SC out into its own module.

layers: Start cutting needless deps between SC and layer_data

---

demos/cube.c
demos/tri.c
include/vulkan/vk_icd.h
layers/core_validation.h
layers/core_validation_error_enums.h
layers/core_validation_types.h
layers/descriptor_sets.h
layers/device_limits.h
layers/image.h
layers/object_tracker.h
layers/swapchain.h
layers/threading.h
layers/vk_layer_utils.cpp
tests/vktestframework.cpp

Fixup invalid C++ variable names in the codebase.

Mark master gh7

---

tests/layer_validation_tests.cpp

There was previously a bug in how old fence dependencies were cleaned
up so this test is being added to prevent any regressions in that
behavior.

tests: Add test for fence submit/wait over multiple frames

---

vk_helper.py

VC++ doesn't support this particular corner of C++11.
Signed-off-by: Chris Forbes <chrisforbes@google.com>

layers: Fix safe struct codegen of static arrays

---

layers/core_validation.cpp
tests/layer_validation_tests.cpp

Contains fixes for issues #704, #655, #716

Fix layout handling in CmdBeginRenderPass, CmdNextSubpass

---

layers/core_validation.cpp

Fixes #689 
Don't issue perf warning if GENERAL layout used in linear tiling case, as GENERAL layout is only valid option in that case.

Tobin gh689 fix

---

tests/layer_validation_tests.cpp

Add a positive test to ensure that the parameter_validation layer ignores
vkUpdateDescriptorSet parameters that are not related to the type of
descriptor set being updated.

tests: vkUpdateDescriptorSet parameter validation

---

layers/core_validation.cpp
layers/core_validation_types.h

Fixed #741 
When a CB is reset (or freed) make sure to remove it from any image/buffer
cb_bindings that it was tied to.
@dustin-lunarg still testing on my side. Can you confirm it fixes bug on your side?

layers: Remove cb_bindings when CB is reset

---

layers/core_validation.cpp
tests/layer_validation_tests.cpp

Fixes #773 
Only make sure that a subpass attachment that has LOAD_OP_CLEAR is not used in *READ_ONLY* layout for its first use. On subsequent uses this is fine.
Also add a positive test that hits this case.
Note that the diff is a bit messy because I moved inputAttachment loop to the bottom. The read code change, though, is checking attach_first_use[index] before calling ValidateLayoutVsAttachmentDescription() and then setting attach_first_use[index] to false.

Tobin gh773 attach first use layout check

---

layers/core_validation.cpp
layers/core_validation_types.h
tests/layer_validation_tests.cpp

Better tracking of valid dynamic scissors & viewports

---

tests/layer_validation_tests.cpp

After adjustment for new extension structures, the
VkLayerTest.InvalidStructPNext vkAllocateMemory and
vkCreateGraphicsPipelines test cases both test the same
validation error.  The larger vkCreateGraphicsPipeline test
case has been removed.

tests: Remove duplicate pNext test

---

tests/layer_validation_tests.cpp

err var is not used in this test

tests: Remove unused var

---

layers/core_validation.cpp

Plumbed function name through for more descriptive error messages from validate_and_update_drawtime_descriptor_state().
Addresses #877 .

GH877 -- Clear up descriptor state validation messages

---

layers/core_validation.cpp
layers/core_validation.h

@tobine, this probably conflicts a bit with your in-flight changes -- but was all mechanical, so can rebuild these patches if you like them after your stuff lands.

Dont copy instance state

---

include/vulkan/vulkan.h
include/vulkan/vulkan.hpp
layers/linux/VkLayer_core_validation.json
layers/linux/VkLayer_image.json
layers/linux/VkLayer_object_tracker.json
layers/linux/VkLayer_parameter_validation.json
layers/linux/VkLayer_swapchain.json
layers/linux/VkLayer_threading.json
layers/linux/VkLayer_unique_objects.json
layers/parameter_validation.cpp
layers/windows/VkLayer_core_validation.json
layers/windows/VkLayer_image.json
layers/windows/VkLayer_object_tracker.json
layers/windows/VkLayer_parameter_validation.json
layers/windows/VkLayer_swapchain.json
layers/windows/VkLayer_threading.json
layers/windows/VkLayer_unique_objects.json
loader/CMakeLists.txt
vk.xml

1.0.32 Vulkan Header Updates

---

demos/smoke/Game.cpp

Change-Id: I9f4371334bf958bb01e89621008b6e569002d9a1

demos: fix gcc warning

---

layers/core_validation.cpp

Change-Id: I152ce109cada7bee85678217f39819ffe51580b9

layers: remove dead code

---

layers/core_validation.cpp
tests/layer_validation_tests.cpp
tests/vkrenderframework.cpp
tests/vkrenderframework.h

Incorporates feedback from @scyganINTEL's original PR #1204, and improves test coverage a bit.

Cort clear dst layout (fixes for #1204)

---

include/vulkan/vulkan.h
include/vulkan/vulkan.hpp
layers/linux/VkLayer_core_validation.json
layers/linux/VkLayer_image.json
layers/linux/VkLayer_object_tracker.json
layers/linux/VkLayer_parameter_validation.json
layers/linux/VkLayer_swapchain.json
layers/linux/VkLayer_threading.json
layers/linux/VkLayer_unique_objects.json
layers/windows/VkLayer_core_validation.json
layers/windows/VkLayer_image.json
layers/windows/VkLayer_object_tracker.json
layers/windows/VkLayer_parameter_validation.json
layers/windows/VkLayer_swapchain.json
layers/windows/VkLayer_threading.json
layers/windows/VkLayer_unique_objects.json
loader/CMakeLists.txt
scripts/generator.py
scripts/lvl_genvk.py
scripts/vk.xml

Also takes care of the issue in PR #1266.
- header:  Updated vulkan.h
- scripts: Updated generator.py
- scripts: Updated vk.xml
- scripts: Merged recent genvk.py changes into lvl_genvk.py
- layers:  Updated json files
- loader:  Updated SOVERSION to 38
- header:  Updated vulkan.hpp

Update to Vulkan header version 1.0.38

---

layers/core_validation.cpp
layers/core_validation.h

Continuing various refactor work in core_validation.
Updated a bunch of functions to use Pre/Post pattern. Renamed some vars. Added some validation flags.
More work to do but submitting this now before PR gets too large.

Tobin more pre post

---

layers/core_validation.cpp

Fixes #1188
Uniformly print all dispatchable handles in error messages as pointers
with the "%p" print specifier.

layers:Update dispatchable object printing

---

tests/layer_validation_tests.cpp

Change-Id: Ifbbbfdc7392214d585be22ce67c6e9a065cb1700

tests: Fix DepthStencilImageViewWithColorAspectBitError

---

layers/vk_validation_stats.py

Update stats script to gather all error enums that are used by tests to
check for validation errors. If the database reports that a test is
checking a specific enum, but that enum is not being used in the
SetDesiredFailureMsg() for that test, report it as a warning.
Ideally all of the checks will start using the explicit enum value to
check for the presence of that error, so this warning will highlight
tests where it should be easy to update them to check for error enum.

scripts:Check for use of error enums in tests

---

tests/vkrenderframework.cpp

Change-Id: Ib7c787e3d54a6504edda6fc74b78da3de456a59f

tests: Place each command on a separate line.

---

layers/core_validation.cpp
layers/descriptor_sets.cpp
layers/image.cpp
layers/vk_validation_stats.py

Remove some duplicate checks, comment on some checks that need new VUs, and add exceptions for some duplicate id uses that are ok.

Tobin dupe unique enum cleanup

---

tests/layer_validation_tests.cpp

Change-Id: Ifdffbb6ac223e938037e71a5adc2868b452e6bd3

tests: Fix ImageFormatLimits

---

CONTRIBUTING.md

Change-Id: I968e503c0c9c107d5e4496e54f68e0e57563fec2

contrib: Update style guide and add Git rules

---

tests/layer_validation_tests.cpp

Change-Id: Ia72c1cb78e0603dd64c81110373b248197cc327f

tests: Fix InvalidPipelineCreateState

---

tests/layer_validation_tests.cpp

Change-Id: I463c083bfa13879bca04090ca8f1a4696def5eb0

tests: Shorten local variable scope

---

tests/layer_validation_tests.cpp

Change-Id: Ic87bcf65452a8181dfb97f1a284a495752689ad9

tests: Fix RenderPassClearOpMismatch

---

layers/core_validation.cpp
layers/object_tracker.cpp
layers/parameter_validation.cpp

Port validation for get_physical_device_properties2 extension over to GitHub now that it's public.

Tobin gpdp2 GitHub merge

---

layers/threading.h
scripts/threading_generator.py

These were skipped due to problems in codegen. Added support for new objects into the layer, fixed codegen.

Add KHR/KHX/NN extensions to threading layer

---

include/vulkan/vulkan.hpp

Change-Id: Ibca9f31b722945f1d96fb41aca0f1e78bd6567f1

headers: Fix vulkan.hpp clang compiler errors

---

layers/parameter_validation.cpp

Added a missing checks for a few validation return codes.

Fix a few parameter validation holes

---

tests/layer_validation_tests.cpp

Add a filter to the error monitor and require explicit function for
unexpected errors. This helps developers easily detect when they
inadvertently add an unexpected error.
Change-Id: I652951fb135795770b06b6805155cd5e4a0e0c62

tests: Prevent new unexpected errors

---

layers/buffer_validation.cpp
tests/layer_validation_tests.cpp

Fixes #1454 
This is the simple fix so getting it in first along with a Positive test to prevent regression.
The layout transition code is getting unwieldy so I plan to do at least a bit of cleanup and consolidation in a follow-on to simplify things a bit.

Tobin gh1454 ds layout validate

---

layers/buffer_validation.cpp
layers/buffer_validation.h
layers/core_validation.cpp

Split up validation/recording, added PreCallXxx routines.

Refactor CmdPipelineBarrier validation 

---

layers/core_validation.cpp
layers/core_validation_types.h

Consider resolve attachments to be written within renderpass

---

tests/layer_validation_tests.cpp

Change-Id: I345b2980ffeefb740d23d73dc8ec15eb955b355e

tests: Fix ImageSampleCounts unexpected errors

---

tests/layer_validation_tests.cpp

Unexpected errors will now cause a test to fail. Explicitly calling
out unexpected errors in the test will still work, but should be used
reluctantly.
Change-Id: I5d121dc453c4acf497643bf10ad02459d0d96f15

tests: Fail on unexpected errors

---

layers/core_validation.cpp
layers/object_tracker.cpp

Fixes GH #1548 and another issue in ObjectTracker.

QueueBindSparse validation fixes

---

tests/layer_validation_tests.cpp

Don't assume format is supported. Check it before use.
Change-Id: Ic74e0fa98612497e57b8264e2c1e025c0b9bd807

tests: Fix device specific failures

---

layers/buffer_validation.cpp
layers/buffer_validation.h
layers/core_validation.cpp
tests/layer_validation_tests.cpp

Started looking at image layout code to add descriptor layout validation and wanted to clean things up a bit first. Still more work to do here and haven't added descriptor validation yet but I'm out for a couple of days so submitting this now and will follow-on with more changes next week.

Tobin gh1476 image descriptor layout

---

layers/buffer_validation.cpp
layers/buffer_validation.h
layers/core_validation.cpp

Simplified source and consolidated usage.
Fixes #714.

Refactor core_validation layer ResolveRemainingLevelsLayers routines

---

layers/core_validation.cpp

Fix handling of depth+stencil formats in shader validation

---

scripts/loader_extension_generator.py

Codegen attempted to construct name definitions instead of pulling from the source XML, causing errors for new header updates.

Fix loader_extensions codegen for name defs

---

layers/unique_objects.cpp

Added unwrapping of vulkan objects embedded in this APIs data buffer.

Add support for vkCmdPushDescriptorSetWithTemplateKHR to unique_objects

---

scripts/helper_file_generator.py

Change-Id: Ia377c52e43442fec17b823c888df6685eff0aca5

scripts: Add ceiling function to vk_struct_size_helper

---

scripts/unique_objects_generator.py

Codegen created wrap/unwrap code on the fly as commands were processed by the XML. Deferred codegen until all the data was complete and collected.   This will be needed in a follow-on patch series to generically handle pNext extension chains.
Note that this does not change the generated code in any way, it only defers the start of output until all the inputs have been processed.

scripts: Defer unique_objects processing

---

include/vulkan/vulkan.h
include/vulkan/vulkan.hpp
layers/linux/VkLayer_core_validation.json
layers/linux/VkLayer_object_tracker.json
layers/linux/VkLayer_parameter_validation.json
layers/linux/VkLayer_swapchain.json
layers/linux/VkLayer_threading.json
layers/linux/VkLayer_unique_objects.json
layers/windows/VkLayer_core_validation.json
layers/windows/VkLayer_object_tracker.json
layers/windows/VkLayer_parameter_validation.json
layers/windows/VkLayer_swapchain.json
layers/windows/VkLayer_threading.json
layers/windows/VkLayer_unique_objects.json
scripts/vk.xml
tests/layers/linux/VkLayer_test.json
tests/layers/linux/VkLayer_wrap_objects.json
tests/layers/windows/VkLayer_test.json
tests/layers/windows/VkLayer_wrap_objects.json

Our farm is down, running through CI before pushing...
- updated include/vulkan/vulkan.h
- updated scripts/vk.xml
- updated layers json files
- updated tests json files
- updated vulkan.hpp

Update header to 1.0.48 Vulkan version

---

layers/core_validation.cpp
layers/parameter_validation.cpp
layers/unique_objects.cpp

Fixed a few DebugReport object type casts and a couple of missed spots with internal object type usage.

Final round of object-type cleanup and wrapping up loose ends

---

tests/run_loader_tests.sh

Tests recently added env var parsing code added to loader.
Change-Id: Ic58d92dfeaed725f02a8f4a79c60d9b4b363aa3f

tests: Add some env var testing to loader tests.

---

layers/core_validation.cpp

Make this consistent with everything else, which uses 'skip'.
Fixes #1655

layers: Invert old 'pass' checks for shader validation

---

layers/core_validation.cpp

Replace the huge switch + duplicated calls with a map of ptr-to-member.
clang-format disabled on the table as it makes a mess.

layers: Convert capability handling to data

---

layers/core_validation.cpp

Allow VK_VALIDATION_CHECK_SHADERS_EXT enum to disable the shaderc-based
shader validation in core_validation.
There were a few other pieces of internal shader validation and
tracking that were tied to the shader_validation bit but I re-enabled
those bits for now as we lose the active descriptor binding tracking if
those features are disabled. That would lead to a various other
features that need to be disabled to avoid crashes. Specifically the
connection between command buffers and active samplers, buffer, images
that are present in descriptor sets.
To test this I ran layer_validation_tests with the shaders disabled
and most tests work fine with only the ones testing internal shader
validation pieces failing as expected.

layers:Pipe in disable for shader validation

---

tests/layer_validation_tests.cpp

- We were passing RENDER_PASS_CONTINUE_BIT in the begin info for the
primary CB, but not continuing a renderpass. This is nonsense, and
crashes some drivers.
- Split up the test and use helpers to make the subtests concise.

tests: Fix (and split) ExecutedUnrecordedCBs test

---

layers/vk_validation_stats.py

Update doc validation to read in the new VUID string and core|ext
columns of the vk_validation_error_database.txt.

scripts:Fix doc validation for 8-col DB

---

tests/layer_validation_tests.cpp
tests/vkrenderframework.cpp
tests/vkrenderframework.h

This is a collection of test simplifications, bugfixes, and dropping of bits of framework that weren't providing any value.

Misc framework fixes

---

layers/device_extensions.h

Param checker is being modified to validate extension dependencies, needs a comprehensive set.

Add new/remaining extensions to device_extensions.h

---

layers/core_validation.cpp
layers/object_tracker.cpp
layers/parameter_validation.cpp
layers/swapchain.cpp
layers/threading.cpp
layers/unique_objects.cpp
layers/vk_layer_data.h

These commits address the leaks reported in #1787 and some more.

Fix a number of memory leaks in validation layers

---

layers/object_tracker.cpp
layers/object_tracker.h
layers/parameter_validation.cpp
layers/threading.cpp
scripts/parameter_validation_generator.py
scripts/threading_generator.py

Same as the previous PR, prolly one more coming for the rest of the layers.

Fix up GetProcAddr handling in object_tracker, threading and parameter_validation layers

---

layers/unique_objects.cpp
scripts/unique_objects_generator.py

All done but for swapchain, which is not long for this life.

Finish up GPA layer cleanup with unique_objects

---

layers/vk_validation_stats.py

layers: Add new source file to stats script

---

layers/shader_validation.cpp
tests/layer_validation_tests.cpp

A couple of things were broken here:
- Patch decoration appears at member level, and was ignored.
- If the block itself has a Location decoration, we assumed it could not be a block

Fix SC confusion on per-patch interface blocks

---

loader/CMakeLists.txt

A previous change of mine broke the ninja build in the loader. This PR resolves that by fixing the include path.

Fix ninja build

---

layers/core_validation.cpp

Heading toward being able to drop the big validation lock around pipeline validation

Untangle some pipeline creation details

---

demos/cube.cpp

Treat suboptimal as success.
Change-Id: I18f0e8592e212c4d1f99294de24cac945bcdb7c3

demos: Add missing break

---

layers/core_validation.cpp
layers/core_validation_types.h
layers/descriptor_sets.cpp
layers/descriptor_sets.h
tests/layer_validation_tests.cpp

Fixes #1869 
Migrate DescriptorSetLayout references to use shared_ptr.

Tobin gh1869 ds shared ptr

---

tests/layer_validation_tests.cpp

Also fixes some unexpected VU errors in this test that were
exposed when the main test accidentally passed. Fixes #1781.

tests: Skip test for 14a004dc if all offsets are valid

---

layers/core_validation.cpp

I want to be able to swap out std::mutex for something the VS
concurrency profiler can see, so let's get all the mentions of it to one
place.

layers: Declare aliases for std::mutex and its RAII wrappers

---

demos/cube.c
demos/cube.cpp

There was a bit of refactoring that creating large changes, tried to break it into manageable pieces.

demos: Add Wayland support to cube/cubepp

---

demos/smoke/CMakeLists.txt
demos/smoke/ShellWayland.cpp
demos/smoke/ShellWayland.h

Change-Id: I82cd3f004410dea1d173ef8022091d6f4463d0f5

demos: Add Wayland input handling to smoketest

---

layers/descriptor_sets.cpp
tests/layer_validation_tests.cpp

Fixes #1941 
Catch the destroyed imageView in a descriptor case instead of asserting.
Updated existing test to include this condition.

Tobin gh1941 ds image view destroyed

---

layers/vu_csv_stats.sh

A simple utility bash script to generate Valid Usage completion
statistics in CSV format, for loading and analyzing in a spreadsheet.
Change-Id: Id45a20ea83d555029cb11418ac5d19c38fd28a15

layers: Add script to create VU stats in CSV

---

layers/core_validation.cpp
layers/descriptor_sets.cpp
layers/descriptor_sets.h

For push descriptor pull DS layout from pipeline layout state instead of creating on the fly.

Tobin simplify push ds

---

tests/layer_validation_tests.cpp

Fixes #2074 
Add test DestroyPipelineRenderPass. This is a positive test that
destroys the renderPass used to create a gfx pipeline and then uses
that pipeline to draw. This makes sure that validation doesn't depend
on the pipeline's renderPass to still be active at the time the
pipeline is used.

tests:Add DestroyPipelineRenderPass

---

layers/core_validation.cpp
tests/layer_validation_tests.cpp

Some renderPass lifetime fixes for validation and associated test updates.

Tobin rm invalid cb rp binding

---

layers/buffer_validation.cpp

From LunarXchange issue:
> I tried to DMA a slice of a cubemap and got this validation error:
> (vkdbg::DS) vkCmdCopyBufferToImage(): pRegion[0].imageExtent (w=1024, h=1024, d=1) dimensions must be even integer multiples of this command buffer's queue family image transfer granularity (w=8, h=8, d=8) or offset (x=0, y=0, z=0) + extent (w=1024, h=1024, d=1) must match the image subresource extents (w=1024, h=1024, d=6).
> It doesn't seem right to apply the depth granularity check to the layer count. The image is 6 layers of {1024,1024,1} so I'm copying the full 'extents'. Also, copying 1 layer of { 1024,1024,6 } would be illegal since the layers have { 1024,1024,1 } extents.
Changed check to ignore depth for 1D, 2D transfers, height for 1D transfers.

Relax MinImageTransferGranularity checks

---

layers/descriptor_sets.cpp
tests/layer_validation_tests.cpp

Potentially fixes #2104 
For Texel Buffers, object_tracker only checks to make sure that the bufferView used in descriptor update is valid. This misses case where buffer underlying the view has been destroyed, which would lead to a crash in CV. Added the check for destroyed buffer and updated existing test to hit that case as well.

Tobin gh2104 buff view ds update

---

layers/descriptor_sets.cpp
tests/layer_validation_tests.cpp

layers: Allow copying nonupdated descriptors

---

tests/layer_validation_tests.cpp

Needed additional format feature checks for the selected formats.  @tobine, can you make sure this takes care of the AMD platform issues?

tests: Fix compressed image copy test

---

CMakeLists.txt
README.md
icd/CMakeLists.txt
icd/README.md
icd/VkICD_mock_icd.def
icd/VkICD_mock_icd.json
layers/CMakeLists.txt
scripts/lvl_genvk.py
scripts/mock_icd_generator.py
tests/layer_validation_tests.cpp

Replacing #2161 
Initial mock ICD commit plus a few updates to get all of the LVL tests passing. Still have about 20 tests with either unexpected errors or that are skipped.

Tobin null icd test cleanup

---

layers/core_validation.cpp
layers/parameter_validation_utils.cpp
tests/layer_validation_tests.cpp
tests/vktestbinding.cpp
tests/vktestbinding.h

Fixes https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2090 and adds tests verify.  Include cleanup changes in independent commits.

Zulauf features2 khr 2090

---

scripts/mock_icd_generator.py

Commented out a couple of debug output statements.
Killed a bunch of comments and code that were carried over from
original script but that are no longer relevant.

scripts:Cleanup comments and output for mock icd

---

BUILD.md
build-android/build_all.sh

A script optimization and document updates (not exhaustive).

Minor Android updates

---

.travis.yml

Run doc validation following build.

tests:Add doc validation to travis CI

---

CMakeLists.txt
layers/shader_validation.cpp
libs/vkjson/vkjson_info.cc
loader/loader.c
tests/layer_validation_tests.cpp

Pulling in #2196 from @null77 along with some build warning fixes.

Win build warn fixes

---

layers/CMakeLists.txt

Fixes duplicate targets in layers / layersvt for VulkanTools
Change-Id: Ieb2577454743ac085153b04b2cbb3fcb25918578

layers: Change target name for devsim json

---

build-android/cmake/README.md
build-android/cmake/layerlib/CMakeLists.txt
build-android/cmake/layerlib/build.gradle

this is mainly to fix https://forums.khronos.org/showthread.php/13651-android-studio-issues?p=42974#post42974
@cnorthrop @tobine please take a look and add other people review too; and if ok, also please merge( I do not have write access)

Update android-build/cmake scripts to build with Android Studio 3.0.0+

---

CMakeLists.txt
icd/CMakeLists.txt
layers/CMakeLists.txt
layers/vk_layer_config.cpp

This is needed to support CI in shared repositories.

Move build of layer_utils from layers cmakefile into root cmakefile

---

layers/core_validation.cpp

Follow-on to #2434 to merge two common loops.

Tobin loop merge

---

tests/layer_validation_tests.cpp

- remove usage of `limits.h` that should not have existed
- merge the two separate handling of `nextafter` direction
- remove workaround for `cmath` impls with missing `std::`
deprecates PR #2443

tests: Clean cmath and climits usage

---

layers/shader_validation.cpp

Enforce fragmentStoresAndAtomics, vertexPipelineStoresAndAtomics features

---

demos/vulkaninfo.c

Added output for extension structures:
VkPhysicalDevice16BitStorageFeaturesKHR
VkPhysicalDeviceSamplerYcbcrConversionFeaturesKHR
VkPhysicalDeviceVariablePointerFeaturesKHR
VkPhysicalDeviceBlendOperationAdvancedFeaturesEXT
VkPhysicalDeviceBlendOperationAdvancedProper-
tiesEXT
VkPhysicalDevicePointClippingPropertiesKHR
VkPhysicalDevicePushDescriptorPropertiesKHR
VkPhysicalDeviceDiscardRectanglePropertiesEXT

vulkaninfo: Add extension output

---

CONTRIBUTING.md

Fixes #2140.  Add guidelines for error message output, including specifying object handles, values, and user assistance on HOW to fix the error.
Will also update our internal docs to match, and this doc receive an overhaul and expansion in the next few weeks.

Update Contributing.md for validation message output information

---

CMakeLists.txt
build-android/android-generate.bat
build-android/android-generate.sh
scripts/helper_file_generator.py
scripts/lvl_genvk.py

This is only used by vktrace, and has been moved to the VulkanTools repository.

Remove struct_size helper file generation and source code

---

scripts/helper_file_generator.py

With 1.1 the VkDebugReportObjectTypeEXT enums are no longer be updated (in favor of the VkObjectType), which meant there is no long a 1-1 relationship with the kVulkanObjectTypes.  Addtionally, handle types that were promoted in 1.1 from extension to core needed special handling given aliasing in the registry.

Fix kVulkanObjectType generation issues w.r.t. 1.1 changes

---

layers/core_validation.cpp

In this case, the last bound state would never be properly configured
and so we'd skip over this whole block.
Fixes #2557

Fix missing validation errors when a CB never bound any descriptor sets

---

layers/buffer_validation.cpp
layers/parameter_validation_utils.cpp

Fix a couple error message formatting errors I missed in PR 2567

Fix formatting errors

---

demos/vulkaninfo.c
loader/cJSON.c
loader/murmurhash.c
scripts/reg.py

Fix/prevent various loader and layer build warnings.

Tobin build warning fixes

---

demos/vulkaninfo.c

Vulkaninfo prints usage information when the "-h" or "--help" option.
Change-Id: I43886920e5ce1feb2e293ed46a3e8c23a217ca69

demos: Vulkaninfo add help flag

---

tests/layer_validation_tests.cpp

Simplified this test by using VkImageObj in place of direct Vulkan
calls.

tests: Simplify CopyImageLayerCountMismatch test

---

loader/loader.c

loader: Fix unhandled out of memory errors

---

layers/buffer_validation.cpp

When a 3D image subresource layout is transitioned via a 2D or 2D_ARRAY image view, all depth slices within the subresource mip levels transition simultaneously, even if the subresource specifies a non-complete set of array layers. Fixed layout recording to reflect this special case.
Another instance of (depth slices == array layers, _except when they don't_.)   ¯\\\_(ツ)\_/¯
Resolves #2136.

Fix an error with 3D image layout transitions
